// Job Role titles for searching
export const JOB_KEYWORDS = [
  "API Test Automation",
  "Cypress Automation Engineer",
  "Director of QA",
  "Head of Quality Engineering",
  "Lead Automation Engineer",
  "Lead QA Engineer",
  "Mobile Automation Engineer",
  "Performance QA Engineer",
  "Performance Test Engineer",
  "Playwright Automation",
  "Principal Automation Engineer",
  "Principal Quality Engineer",
  "Principal SDET",
  "Python Automation",
  "QA Automation Architect",
  "QA Automation Lead",
  "QA Manager (Automation)",
  "Quality Engineering Lead",
  "SDET Lead",
  "Selenium Automation",
  "Senior Automation Engineer",
  "Senior QA Automation Engineer",
  "Senior SDET (Software Development Engineer in Test)",
  "Senior Test Automation Engineer",
  "Senior Test Automation Specialist",
  "Senior Test Engineer",
  "Staff SDET Automation Engineer",
  "Staff Software Development Engineer in Test",
  "Test Automation Lead",
];

// Classification Categories, keywords and negative associations.
export const CATEGORIES = {
  SoftwareDEV: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "software engineer",
      "full stack",
      "application developer",
      "web developer",
      "solution architect",
      "software architect",
      "api development",
      "design patterns",
      "microservices",
      "rest api",
      "solution engineer",
      "feature engineering",
      "model training",
      "data pipeline",
      "computer vision",
    ],
    terms: [
      "developer",
      "programmer",
      "frontend",
      "backend",
      "mobile",
      "javascript",
      "typescript",
      "java",
      "c#",
      ".net",
      "python",
      "golang",
      "go",
      "ruby",
      "php",
      "swift",
      "kotlin",
      "scala",
      "rust",
      "c++",
      "objective-c",
      "node.js",
      "nodejs",
      "react",
      "angular",
      "vue",
      "svelte",
      "jquery",
      "spring",
      "spring boot",
      "django",
      "flask",
      "fastapi",
      "rails",
      "laravel",
      "express.js",
      "graphql",
      "apollo",
      "architecture",
      "oop",
      "functional programming",
      "sql",
      "nosql",
      "mongodb",
      "postgres",
      "mysql",
      "database",
      "algorithm",
      "data structures",
      "coding",
      "genai",
      "rag",
      "sagemaker",
      "bedrock",
    ],
    negative: [
      // QA / Testing
      "qa",
      "quality",
      "tester",
      "sdet",
      "automation tester",
      "test plan",
      "test case",
      "manual testing",
      "bug tracking",
      "regression testing",
      // DevOps/SRE
      "devops",
      "sre",
      "site reliability",
      "platform engineer",
      "infrastructure",
      "ci/cd",
      "jenkins",
      "prometheus",
      "grafana",
      "on-call",
      "incident",
      // Hardware/Mech
      "hardware",
      "pcb",
      "rtl",
      "fpga",
      "asic",
      "embedded",
      "firmware",
      "oscilloscope",
      "mechanical",
      "mechatronics",
      "electromechanical",
      "3d cad",
      "piping",
      // Non-dev recruiting/ops
      "talent acquisition",
      "recruitment",
      "hiring",
      "sourcing candidates",
      "offer letter",
      "compensation",
      "procurement",
      "vendor management",
      "supplier",
      "iso 9001",
      "supply chain",
      // Construction & civil
      "civil",
      "construction",
      "mep",
      // Out-of-scope tech mgmt
      "product manager",
      "project manager",
      "agile coach",
      "scrum master",
      "business intelligence",
    ],
  },

  SoftwareQA: {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "quality engineer",
      "quality assurance",
      "test engineer",
      "software developer in test",
      "test case",
      "test plan",
      "test strategy",
      "test execution",
      "bug report",
      "api testing",
      "ui testing",
      "regression testing",
      "functional testing",
      "performance testing",
      "load testing",
      "acceptance testing",
      "integration testing",
      "e2e testing",
      "black box",
      "white box",
      "software quality engineer",
      "manual and automation testing",
      "test coverage",
      "defect tracking",
      "defect triage",
      "testing web applications",
      "qa automation",
      "qa specialist",
      "qa architect",
      "selenium testing",
      "rest assured",
      "ready api",
      "smoke test",
      "test management tools",
      "root cause analysis",
      "agile qa",
      "compliance testing",
    ],
    terms: [
      "qa",
      "quality",
      "tester",
      "testing",
      "sdet",
      "automation",
      "selenium",
      "seleniumbase",
      "cypress",
      "playwright",
      "postman",
      "soapui",
      "jmeter",
      "testrail",
      "qtest",
      "jira",
      "appium",
      "webdriverio",
      "k6",
      "gatling",
      "sonarqube",
      "uipath test",
      "tosca",
      "tdd",
      "bdd",
      "defect",
      "manual testing",
      "validation",
      "logs",
      "testng",
      "junit",
      "zephyr",
      "post-release",
      "post-implementation",
      "bug bash",
      "sanity testing",
      "smoke testing",
    ],
    negative: [
      // Hardware
      "hardware",
      "pcb",
      "rtl",
      "firmware",
      "fpga",
      "asic",
      "oscilloscope",
      "electrical",
      // DevOps/SRE
      "sre",
      "site reliability",
      "platform engineer",
      "on-call",
      "incident management",
      // Pure architecture build roles
      "software architect",
      "building features",
      // Construction/Civil/Manufacturing
      "mep",
      "civil",
      "civil engineering",
      "construction",
      "plumbing",
      "fire fighting",
      "real estate",
      "residential construction",
      "structural",
      // Industry QA that is not SoftwareQA (we avoid misclassifying):
      "qms",
      "snagging",
      "sop",
      "itp",
      // Heavier BI/warehouse (goes to DataEngg)
      "data warehousing",
      "etl",
      // Non-tech roles
      "talent acquisition",
      "recruitment",
      "hiring",
      "mechanical",
      "casting",
      "machining",
      "manufacturing",
      "emotor",
      "electric vehicle",
      "procurement",
      "vendor management",
      "contracts",
      "supplier",
      "iso 9001",
      "cost-saving",
      "logistics",
      "supply chain",
      // Product/Program
      "product roadmap",
      "stakeholder management",
      "budget",
      // Pharma
      "gmp",
      "cgmp",
      "fda",
      "apqr",
      "qms",
      "validation protocol",
      "21 cfr",
      "sop",
      "biosimilars",
    ],
  },

  HardwareQA: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "hardware test",
      "validation engineer",
      "system validation",
      "silicon validation",
      "post-silicon",
      "pre-silicon",
      "board bring-up",
      "manufacturing test",
      "power integrity",
      "mechanical engineer",
      "mechanical design engineer",
      "electric motor",
      "electric vehicle",
      "manufacturing drawings",
      "bill of materials",
      "component development",
      "industrial manufacturing",
      "geometric dimensioning",
      "gd&t",
      "manufacturing processes",
      "additive manufacturing",
      "aluminum die casting",
      "plastic injection moulding",
    ],
    terms: [
      "hardware",
      "pcb",
      "rtl",
      "fpga",
      "asic",
      "embedded",
      "firmware",
      "board design",
      "schematic",
      "layout",
      "lab",
      "oscilloscope",
      "signal integrity",
      "logic analyzer",
      "spectrum analyzer",
      "jtag",
      "debugger",
      "multimeter",
      "test fixture",
      "electrical",
      "bench testing",
      "emc",
      "emi",
      "mechatronics",
      "electromechanical",
      "3d cad",
      "sensors",
      "valves",
      "fmea",
      "prototypes",
      "emotor",
      "automotive",
      "drivetrain",
      "casting",
      "machining",
      "stamping",
      "catia",
      "ansys",
    ],
    negative: [
      // Software/web
      "web",
      "frontend",
      "backend",
      "microservices",
      "ui",
      "api testing",
      "react",
      "node.js",
      "javascript",
      "css",
      "html",
      "java",
      "c#",
      "full stack",
      // Cloud/devops
      "cloud",
      "aws",
      "gcp",
      "azure",
      "devops",
      "sre",
      "ci/cd",
      // Non-relevant
      "mep",
      "civil",
      "construction",
      "plumbing",
      "talent acquisition",
      "recruitment",
      "hiring",
      "product roadmap",
      "stakeholder management",
      "etl",
      "data lake",
      // Pharma
      "apqr",
      "biosimilars",
      "oos",
      "21 cfr",
      "batch record",
      "vmp",
    ],
  },
  PharmaQA: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "quality management system",
      "gmp compliance",
      "process validation",
      "computer system validation",
      "apqr",
      "quality oversight",
      "regulatory audits",
      "batch record review",
      "corrective and preventive action",
      "change control management",
      "quality control for pharma",
      "inspection readiness",
      "validation protocol and report",
      "quality operations and gmp",
      "biosimilar operations",
      "system compliance",
      "design control quality management",
    ],
    terms: [
      "qms",
      "gmp",
      "cgmp",
      "fda",
      "ema",
      "oos",
      "capa",
      "apqr",
      "validation",
      "protocol",
      "report",
      "tpms", // Third-Party Manufacturers
      "biosimilars",
      "pharmaceutical",
      "biotech",
      "medical device",
      "audit",
      "inspection",
      "deviation",
      "change control",
      "batch processing",
      "sop",
      "bpr", // Batch Production Record / Batch Processing Record
      "bmr", // Batch Manufacturing Record
      "dcs", // Document Control System
      "ensur", // Specific system name (ENSUR 4.2)
      "iso13485",
      "eumdd",
      "iec 62304",
      "21 cfr part",
      "vmp", // Validation Master Plan
      "csv", // Computer System Validation
      "iq", // Installation Qualification
      "oq", // Operational Qualification
      "pq", // Performance Qualification
      "risk assessment",
      "quality review",
      "pharma",
      "hipaa",
      "argus safety",
      "health science",
    ],
    negative: [
      // Exclude generic SoftwareQA terms unless paired with Pharma terms
      "selenium",
      "cypress",
      "python",
      "javascript",
      "java",
      "ui testing",
      "api testing",
      "sdet",
      // Exclude pure HardwareQA/Engineering terms
      "pcb",
      "rtl",
      "fpga",
      "mechanical",
      "electromechanical",
      "3d cad",
      // Exclude generic IT roles (unless compliance/validation)
      "full stack",
      "backend",
      "frontend",
      "microservices",
      "devops",
      "sre",
      "kubernetes",
    ],
  },

  "DevOps/SRE": {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "site reliability",
      "platform engineer",
      "infrastructure engineer",
      "service mesh",
      "infrastructure as code",
      "platform as code",
      "incident management",
      "high availability",
      "disaster recovery",
    ],
    terms: [
      "devops",
      "sre",
      "reliability engineer",
      "cloud engineer",
      "kubernetes",
      "k8s",
      "docker",
      "helm",
      "terraform",
      "ansible",
      "puppet",
      "chef",
      "saltstack",
      "container",
      "ci/cd",
      "github actions",
      "jenkins",
      "gitlab ci",
      "circleci",
      "travis ci",
      "prometheus",
      "grafana",
      "observability",
      "pagerduty",
      "datadog",
      "cloudwatch",
      "splunk",
      "elk",
      "elasticsearch",
      "logstash",
      "kibana",
      "new relic",
      "cloud",
      "aws",
      "gcp",
      "azure",
      "istio",
      "envoy",
      "on-call",
      "incident",
      "postmortem",
      "iac",
      "automation",
      "scripting",
      "bash",
      "powershell",
      "slo",
      "sli",
      "sla",
      "scalability",
      "monitoring",
      "logging",
      "alerting",
    ],
    negative: [
      "manual testing",
      "test case",
      "ui automation",
      "qa",
      "quality assurance",
      "sdet",
      "test plan",
      "bug report",
      "selenium",
      "cypress",
      "frontend",
      "react",
      "angular",
      "vue",
      "ui/ux",
      "application developer",
      "hardware",
      "pcb",
      "fpga",
      "embedded",
      "firmware",
      "oscilloscope",
      "rtl",
      "talent acquisition",
      "recruitment",
      "hiring",
      "sourcing candidates",
      "offer letter",
      "compensation",
      "civil",
      "construction",
      "mep",
      "automotive",
      "mechanical",
      "product strategy",
      "business analyst",
      "scrum master",
      "tableau",
      "procurement",
      "vendor management",
      "supplier",
      "supply chain",
    ],
  },

  DataEngg: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "data engineer",
      "etl developer",
      "data pipeline",
      "data warehousing",
      "business intelligence",
      "big data",
      "data modeling",
      "data governance",
      "data quality assurance",
      "master data management",
      "analytics engineer",
    ],
    terms: [
      "spark",
      "hadoop",
      "hive",
      "kafka",
      "airflow",
      "etl",
      "elt",
      "data lake",
      "databricks",
      "dbt",
      "tableau",
      "power bi",
      "qlik",
      "snowflake",
      "redshift",
      "dynamodb",
      "bigquery",
      "nosql",
      "ssis",
      "ssas",
      "ssrs",
      "data vault",
      "fivetran",
      "stitch",
      "glue",
      "lakehouse",
    ],
    negative: [
      "frontend",
      "ui",
      "ux",
      "react",
      "angular",
      "vue",
      "mobile",
      "qa",
      "tester",
      "sdet",
      "manual testing",
      "firmware",
      "hardware",
      "pcb",
      "fpga",
      "oscilloscope",
      "mechanical",
      "incident management",
      "on-call",
      "kubernetes",
      "scrum master",
      "product roadmap",
      "stakeholder",
    ],
  },

  "ML/AI": {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "data scientist",
      "machine learning scientist",
      "applied scientist",
      "ml engineer",
      "ml research",
      "research scientist",
      "computer vision",
      "natural language processing",
      "nlp",
      "recommendation systems",
      "time series forecasting",
      "experiment design",
      "ab testing",
    ],
    terms: [
      "ml",
      "ai",
      "llm",
      "genai",
      "rag",
      "prompt engineering",
      "feature engineering",
      "model training",
      "model evaluation",
      "model tuning",
      "hyperparameter",
      "pytorch",
      "tensorflow",
      "sklearn",
      "xgboost",
      "lightgbm",
      "huggingface",
      "vector db",
      "faiss",
      "milvus",
      "weaviate",
      "sagemaker",
      "bedrock",
      "comet",
      "wandb",
      "mlflow",
      "notebook",
      "statistics",
      "bayesian",
      "regression",
      "classification",
      "clustering",
      "experiment tracking",
      "offline evaluation",
      "online metrics",
    ],
    negative: [
      "test case",
      "manual testing",
      "qa",
      "tester",
      "on-call",
      "incident",
      // DevOps
      "jenkins",
      "terraform",
      "kubernetes",
      "pcb",
      "rtl",
      "fpga",
      // Hardware
      "oscilloscope",
      "talent acquisition",
      "recruitment",
      "hiring",
      "product roadmap",
      "stakeholder management",
    ],
  },

  Security: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "security engineer",
      "application security",
      "cloud security",
      "product security",
      "security analyst",
      "security operations",
      "soc analyst",
      "penetration testing",
      "red team",
      "blue team",
      "threat detection",
      "security architecture",
      "identity and access management",
      "iam",
      "governance risk compliance",
      "grc",
      "risk management",
      "vulnerability management",
      "terminal security",
      "security operations",
      "access control and key management",
      "mock drills",
      "vvip movement",
    ],
    terms: [
      "infosec",
      "appsec",
      "secops",
      "siem",
      "soar",
      "splunk",
      "qrader",
      "sentinel",
      "crowdstrike",
      "okta",
      "auth0",
      "sso",
      "mfa",
      "oidc",
      "oauth",
      "nist",
      "iso 27001",
      "soc2",
      "pci-dss",
      "hipaa",
      "gdpr",
      "burp",
      "zap",
      "nessus",
      "qualys",
      "osint",
      "mitre att&ck",
      "owasp",
      "secrets scanning",
      "sast",
      "dast",
      "sca",
      "key management",
      "access control",
      "biometric",
      "concessionaires",
    ],
    negative: [
      "qa",
      "tester",
      "manual testing",
      "frontend",
      "react",
      "angular",
      "vue",
      "pcb",
      "fpga",
      "oscilloscope",
      "etl",
      "data warehousing",
      "scrum master",
      "product manager",
    ],
  },

  RPA: {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "rpa developer",
      "uipath developer",
      "automation anywhere developer",
      "blue prism developer",
      "robotic process automation",
      "attended automation",
      "unattended automation",
      "UiPath Orchestrator",
      "UiPath Studio",
      "UiPath Assistant",
      "UiPath ReFramework",
      "UiPath Document Understanding",
      "UiPath AI Center",
      "UiPath Action Center",
      "UiPath Insights",
      "UiPath Governance",
      "UiPath Deployment",
      "UiPath Licensing",
      "UiPath Queue Management",
      "UiPath Trigger Management",
      "UiPath Asset Management",
      "UiPath Package Deployment",
      "UiPath Marketplace",
    ],
    terms: [
      "uipath",
      "automation anywhere",
      "blue prism",
      "orchestrator",
      "reframework",
      "workflow analyzer",
      "invoke workflow",
      "custom activity",
      "robot provisioning",
      "package publishing",
      "transaction item",
      "queue trigger",
      "automation hub",
      "document understanding",
      "ocr engines",
      "ai fabric",
      "action center",
      "insights dashboard",
    ],
    negative: [
      "qa",
      "test case",
      "manual testing",
      "kubernetes",
      "terraform",
      "jenkins",
      "pcb",
      "rtl",
      "fpga",
      // Physical/Aviation Security / Airport Ops
      "immigration",
      "customs",
      "airport",
      "terminal",
      "igia",
      "skytrax",
      "security operations",
      "key management",
      "access control",
      "biometric access",
      "mock drills",
      "vvip",
      "touting",
      "concessionaires",
      "house keeping agencies",
      // Cyber/DevOps terms
      "kubernetes",
      "terraform",
      "prometheus",
      "grafana",
      // QA specific test frameworks
      "selenium",
      "cypress",
      "postman",
      "api testing",
      "test case",
      "sdet",
      "recruitment",
      "talent acquisition",
      "hiring",
    ],
  },

  DBA: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "database administrator",
      "database reliability engineer",
      "performance tuning",
      "backup and recovery",
      "disaster recovery",
      "replication",
      "high availability",
    ],
    terms: [
      "oracle dba",
      "sql server dba",
      "mysql dba",
      "postgres dba",
      "pl/sql",
      "t-sql",
      "indexing",
      "query tuning",
      "partitioning",
      "rds",
      "aurora",
      "exadata",
      "asm",
      "golden gate",
      "logical replication",
    ],
    negative: [
      "etl",
      "spark",
      "airflow",
      "kubernetes",
      "terraform",
      "selenium",
      "cypress",
      "pcb",
      "rtl",
    ],
  },

  Management: {
    weight: 1,
    titleBoost: 1.8,
    phrases: [
      "product manager",
      "project manager",
      "scrum master",
      "agile coach",
      "product owner",
      "business analyst",
      "product strategy",
      "product roadmap",
      "stakeholder management",
      "user stories",
      "requirements gathering",
      "go-to-market",
      "pmp certified",
      "program manager",
      "delivery manager",
    ],
    terms: [
      "agile",
      "scrum",
      "kanban",
      "pmp",
      "csm",
      "jira",
      "confluence",
      "trello",
      "wbs",
      "budgeting",
      "timeline",
      "risk management",
      "stakeholder",
      "feature",
      "release",
      "mvp",
      "okr",
      "kpi",
      "gantt",
      "project",
      "product",
      "management",
      "analyst",
      "ux research",
      "market research",
      "roadmap",
      "portfolio",
    ],
    negative: [
      "coding",
      "javascript",
      "python",
      "java",
      "c#",
      "sql",
      "api development",
      "full stack",
      "backend",
      "frontend",
      "developer",
      "engineer",
      "qa",
      "tester",
      "sdet",
      "manual testing",
      "automation",
      "kubernetes",
      "terraform",
      "devops",
      "sre",
      "hardware",
      "pcb",
      "rtl",
      "firmware",
      "procurement",
      "vendor management",
      "supplier",
      "supply chain",
    ],
  },
};

// Role-defining title nudges only (specific > generic). Order matters.
export const TITLE_NUDGES = [
  // --- SoftwareQA ---
  {
    regex: /\b(sdet|software\s*developer\s*in\s*test)\b/i,
    cat: "SoftwareQA",
    boost: 5,
  },
  {
    regex:
      /\b(qa\s*engineer|quality\s*engineer|test\s*automation|automation\s*tester)\b/i,
    cat: "SoftwareQA",
    boost: 4,
  },
  {
    regex: /\b(test\s*architect|qa\s*architect)\b/i,
    cat: "SoftwareQA",
    boost: 3,
  },

  // --- DevOps / SRE / Platform (infra) ---
  {
    regex: /\b(sre|site\s*reliability\s*engineer)\b/i,
    cat: "DevOps/SRE",
    boost: 5,
  },
  {
    regex:
      /\b(devops|platform\s*engineer|production\s*engineer|infrastructure\s*engineer)\b/i,
    cat: "DevOps/SRE",
    boost: 4,
  },

  // --- HardwareQA / Embedded / Silicon / Mechanical ---
  {
    regex:
      /\b(asic|fpga|rtl|post-?silicon|pre-?silicon|silicon\s*validation)\b/i,
    cat: "HardwareQA",
    boost: 5,
  },
  {
    regex:
      /\b(hardware|embedded|firmware|validation\s*engineer|mechatronics|electro-?mechanical|mechanical)\b/i,
    cat: "HardwareQA",
    boost: 4,
  },

  // --- Data Engineering / Analytics Engineering ---
  {
    regex:
      /\b(data\s*engineer|analytics\s*engineer|data\s*platform\s*engineer)\b/i,
    cat: "DataEngg",
    boost: 4,
  },
  {
    regex: /\b(etl\s*developer|data\s*architect)\b/i,
    cat: "DataEngg",
    boost: 3,
  },

  // --- Data Science / ML ---
  {
    regex: /\b(data\s*scientist|applied\s*scientist|research\s*scientist)\b/i,
    cat: "ML/AI",
    boost: 4,
  },
  // Ambiguous but useful signal; let description/keyword scoring finalize
  {
    regex:
      /\b(ml\s*engineer|machine\s*learning\s*engineer|computer\s*vision|nlp)\b/i,
    cat: "ML/AI",
    boost: 3,
  },

  // --- Security / InfoSec ---
  {
    regex:
      /\b(application\s*security|appsec|security\s*engineer|product\s*security|cloud\s*security)\b/i,
    cat: "Security",
    boost: 4,
  },
  {
    regex:
      /\b(soc\s*analyst|penetration\s*tester|red\s*team|blue\s*team|grc|governance\s*risk\s*compliance|iam)\b/i,
    cat: "Security",
    boost: 4,
  },

  // --- RPA / UiPath ---
  {
    regex:
      /\b(rpa\s*developer|uipath\s*developer|automation\s*anywhere\s*developer|blue\s*prism\s*developer|rpa\s*engineer)\b/i,
    cat: "RPA",
    boost: 5,
  },
  {
    regex: /\b(re-framework|robotic\s*process\s*automation)\b/i,
    cat: "RPA",
    boost: 4,
  },

  // --- DBA ---
  {
    regex:
      /\b(database\s*administrator|dba|database\s*reliability\s*engineer)\b/i,
    cat: "DBA",
    boost: 5,
  },
  {
    regex: /\b(oracle\s*dba|sql\s*server\s*dba|postgres\s*dba|mysql\s*dba)\b/i,
    cat: "DBA",
    boost: 5,
  },

  // --- Management / PM / Program / Scrum ---
  {
    regex:
      /\b(product\s*manager|project\s*manager|program\s*manager|delivery\s*manager|product\s*owner|scrum\s*master|agile\s*coach)\b/i,
    cat: "Management",
    boost: 5,
  },

  // --- Pharma QA ---
  {
    regex: /\b(computer\s*system\s*validation|csv)\b/i,
    cat: "PharmaQA",
    boost: 5,
  },
  {
    regex: /\b(gxp|cgmp|gmp)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(quality\s*management\s*system|qms)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(pharma\s*quality|medical\s*device\s*qa|biotech\s*qa)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(validation\s*specialist|validation\s*scientist)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex:
      /\b(regulatory\s*compliance|inspection\s*readiness|quality\s*auditor)\b/i,
    cat: "PharmaQA",
    boost: 3,
  },
  {
    regex: /\b(capa|apqr|change\s*control)\b/i,
    cat: "PharmaQA",
    boost: 3,
  },
];
