// Job Role titles for searching
export const JOB_KEYWORDS = [
  // --- Core Individual Contributor Roles ---
  "Automation Engineer",
  "Automation Test Engineer",
  "QA Analyst",
  "QA Automation Engineer",
  "Quality Analyst",
  "Quality Assurance Engineer",
  "Quality Engineer",
  "SDET",
  "Software Development Engineer in Test",
  "Software QA Engineer",
  "Software Test Engineer",
  "Test Automation Engineer",
  "Test Engineer",

  // --- Specialized / Tool Specific ---
  "API Test Automation Engineer",
  "Cypress Automation Engineer",
  "Mobile Automation Engineer",
  "Mobile QA Engineer",
  "Performance QA Engineer",
  "Performance Test Engineer",
  "Playwright Automation Engineer",
  "Python Automation Engineer",
  "Selenium Automation Engineer",

  // --- Senior / Staff / Principal ---
  "Principal Automation Engineer",
  "Principal Quality Engineer",
  "Principal SDET",
  "Senior Automation Engineer",
  "Senior QA Automation Engineer",
  "Senior QA Engineer",
  "Senior SDET",
  "Senior Software Development Engineer in Test",
  "Senior Test Automation Engineer",
  "Senior Test Engineer",
  "Staff SDET",
  "Staff Software Development Engineer in Test",
  "Member of Technical Staff QA",
  "Member of Technical Staff SDET",
  "Senior Member of Technical Staff QA",
  "Principal Member of Technical Staff QA",

  // --- Leadership / Management ---
  "Director of QA",
  "Director of Quality Engineering",
  "Head of Quality Engineering",
  "Lead Automation Engineer",
  "Lead QA Engineer",
  "QA Automation Architect",
  "QA Automation Lead",
  "QA Manager",
  "Quality Engineering Lead",
  "Quality Engineering Manager",
  "SDET Lead",
  "Test Automation Lead",

  // -- Dev roles ---
  "SDE I",
  "SDE II",
  "SDE III",
  "Software Development Engineer",
  "Backend Software Engineer",
  "Frontend Software Engineer",
  "Full Stack Developer",
  "Site Reliability Engineer",
  "Principal Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Director of Software Development",
  "Engineering Lead",
  "Engineering Manager",
  "Lead Software Engineer",
  "Software Architect",
  "Software Engineering Manager",
  "Team Lead",
  "Technical Lead",
  "Vice President of Engineering",
];

// LinkedIn Job Search Query to get recent posts
export const LINKEDIN_SEARCH_QUERY = {
  location: "India",
  jobType: "full time",
  sortBy: "recent", // relevant or recent
  dateSincePosted: "24hr",
  experienceLevel: "senior",
  //valid values: internship, entry level, associate, senior, director, executive
  limit: "20",
  page: "0",
};

export const DATA_TABLE_CONFIG = {
  // Sort by the 5th column (Date Posted) descending
  // order: [[4, "desc"]],
  order: [],
  pageLength: 10, // Show 10 rows per page
  lengthChange: true, // Allow user to change page length
  responsive: true, // Make table responsive
  autoWidth: false, // Prevent automatic column width
  language: {
    search: "Search jobs:",
    lengthMenu: "Show _MENU_ job posts per page",
    info: "Showing _START_ to _END_ of _TOTAL_ job posts",
  },
  columnDefs: [
    {
      // 1. Job Title (Index 0)
      targets: [0],
      className: "dt-head-left dt-body-left", // Ensure header and body text align left
      width: "30%",
    },
    {
      // 2. Company Name (Index 1)
      targets: [1],
      className: "dt-head-left dt-body-left ellipsis",
      width: "15%",
    },
    {
      // 3. Location (Index 2)
      targets: [2],
      className: "dt-head-left dt-body-left ellipsis",
      width: "15%",
    },
    {
      // 4. Type (Index 3 - QA / DEV / DEVOPS roles)
      targets: [3],
      className: "dt-head-center dt-body-center", // Center align for better visual grouping
      width: "15%",
    },
    {
      // 5. Years of Experience (Index 4)
      targets: [4],
      className: "dt-head-center dt-body-center",
      width: "7%",
    },
    {
      // 6. Emploee count (Index 5)
      targets: [5],
      className: "dt-head-center dt-body-center",
      width: "8%",
    },
    {
      // 7. Date Posted (Index 6)
      targets: [6],
      type: "date", // Explicitly tell DataTables to sort this as a date
      className: "dt-head-right dt-body-right text-nowrap", // Align right and prevent wrapping
      width: "10%",
    },
  ],
};

// Classification Categories, keywords and negative associations.
export const CATEGORIES = {
  SoftwareDEV: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "software engineer",
      "full stack",
      "application developer",
      "web developer",
      "solution architect",
      "software architect",
      "api development",
      "design patterns",
      "microservices",
      "rest api",
      "solution engineer",
      "feature engineering",
      "model training",
      "data pipeline",
      "computer vision",
      "salesforce developer",
      "salesforce technical lead",
      "apex developer",
      "lightning web components",
      "oracle fusion",
      "erp consultant",
      "functional consultant",
      "technical lead",
      "full-stack engineer",
      "technical mentorship",
      "distributed systems",
      "network programming",
      "ethernet switching",
    ],
    terms: [
      "developer",
      "programmer",
      "frontend",
      "backend",
      "mobile",
      "javascript",
      "typescript",
      "java",
      "c#",
      ".net",
      "python",
      "golang",
      "go",
      "ruby",
      "php",
      "swift",
      "kotlin",
      "scala",
      "rust",
      "c++",
      "objective-c",
      "node.js",
      "nodejs",
      "react",
      "angular",
      "vue",
      "svelte",
      "jquery",
      "spring",
      "spring boot",
      "django",
      "flask",
      "fastapi",
      "rails",
      "laravel",
      "express.js",
      "graphql",
      "apollo",
      "architecture",
      "oop",
      "functional programming",
      "sql",
      "nosql",
      "mongodb",
      "postgres",
      "mysql",
      "database",
      "algorithm",
      "data structures",
      "coding",
      "genai",
      "rag",
      "sagemaker",
      "bedrock",
      "salesforce",
      "apex",
      "lwc",
      "soql",
      "visualforce",
      "oracle",
      "erp",
      "s4hana",
      "peoplesoft",
      "netsuite",
      "workday",
      "code reviews",
      "front-end",
      "back-end",
      "architecture",
      "debugging",
      "c++",
      "c",
      "sdk",
      "vxlan",
      "architecture",
    ],
    negative: [
      // QA / Testing
      "qa",
      "quality",
      "tester",
      "sdet",
      "automation tester",
      "test plan",
      "test case",
      "manual testing",
      "bug tracking",
      "regression testing",
      // DevOps/SRE
      "devops",
      "sre",
      "site reliability",
      "platform engineer",
      "infrastructure",
      "ci/cd",
      "jenkins",
      "prometheus",
      "grafana",
      "on-call",
      "incident",
      // Hardware/Mech
      "hardware",
      "pcb",
      "rtl",
      "fpga",
      "asic",
      "embedded",
      "firmware",
      "oscilloscope",
      "mechanical",
      "mechatronics",
      "electromechanical",
      "3d cad",
      "piping",
      // Non-dev recruiting/ops
      "talent acquisition",
      "recruitment",
      "hiring",
      "sourcing candidates",
      "offer letter",
      "compensation",
      "procurement",
      "vendor management",
      "supplier",
      "iso 9001",
      "supply chain",
      // Construction & civil
      "civil",
      "construction",
      "mep",
      // Out-of-scope tech mgmt
      "product manager",
      "project manager",
      "agile coach",
      "scrum master",
      "business intelligence",
      "recruitment",
      "hr",
      "human resources",
      "sales",
      "marketing",
      "customer support",
      "bpo",
      "kpo",
      "call center",
      "process associate",
      "uvm",
      "verilog",
      "systemverilog",
      "asic",
      "rtl",
      "fpga",
      "hardware",
      "oscilloscope",
    ],
  },

  SoftwareQA: {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "quality engineer",
      "quality assurance",
      "test engineer",
      "software developer in test",
      "test case",
      "test plan",
      "test strategy",
      "test execution",
      "bug report",
      "api testing",
      "ui testing",
      "regression testing",
      "functional testing",
      "performance testing",
      "load testing",
      "acceptance testing",
      "integration testing",
      "e2e testing",
      "black box",
      "white box",
      "software quality engineer",
      "manual and automation testing",
      "test coverage",
      "defect tracking",
      "defect triage",
      "testing web applications",
      "qa automation",
      "qa specialist",
      "qa architect",
      "selenium testing",
      "rest assured",
      "ready api",
      "smoke test",
      "test management tools",
      "root cause analysis",
      "agile qa",
      "compliance testing",
      "sap testing",
      "sap qm",
      "user acceptance testing",
      "uat lead",
      "test delivery",
      "quality engineering lead",
      "manual test lead",
      "qa lead",
      "test lead",
      "manual testing",
      "functional test lead",
      "sap qm",
      "quality management module",
      "csv validation",
      "user acceptance testing",
    ],
    terms: [
      "qa",
      "quality",
      "tester",
      "testing",
      "sdet",
      "automation",
      "selenium",
      "seleniumbase",
      "cypress",
      "playwright",
      "postman",
      "soapui",
      "jmeter",
      "testrail",
      "qtest",
      "jira",
      "appium",
      "webdriverio",
      "k6",
      "gatling",
      "sonarqube",
      "uipath test",
      "tosca",
      "tdd",
      "bdd",
      "defect",
      "manual testing",
      "validation",
      "logs",
      "testng",
      "junit",
      "zephyr",
      "post-release",
      "post-implementation",
      "bug bash",
      "sanity testing",
      "smoke testing",
      "sap",
      "ecc",
      "s4hana",
      "crm testing",
      "erp testing",
    ],
    negative: [
      // Hardware
      "hardware",
      "pcb",
      "rtl",
      "firmware",
      "fpga",
      "asic",
      "oscilloscope",
      "electrical",
      "systemverilog",
      "asic",
      "fpga",
      "hardware",
      "oscilloscope",
      "silicon",
      "post-silicon",
      "pcie",
      "interconnect",
      "physical layer",
      // DevOps/SRE
      "sre",
      "site reliability",
      "platform engineer",
      "on-call",
      "incident management",
      // Pure architecture build roles
      "software architect",
      "building features",
      // Construction/Civil/Manufacturing
      "mep",
      "civil",
      "civil engineering",
      "construction",
      "plumbing",
      "fire fighting",
      "real estate",
      "residential construction",
      "structural",
      // Industry QA that is not SoftwareQA (we avoid misclassifying):
      "qms",
      "snagging",
      "sop",
      "itp",
      // Heavier BI/warehouse (goes to DataEngg)
      "data warehousing",
      "etl",
      // Non-tech roles
      "talent acquisition",
      "recruitment",
      "hiring",
      "mechanical",
      "casting",
      "machining",
      "manufacturing",
      "manufacturing environment",
      "pumps",
      "valves",
      "compressors",
      "emotor",
      "electric vehicle",
      "procurement",
      "vendor management",
      "contracts",
      "supplier",
      "iso 9001",
      "cost-saving",
      "logistics",
      "supply chain",
      // Product/Program
      "product roadmap",
      "stakeholder management",
      "budget",
      "external quality audits",
      "raw materials",
      // Pharma
      "gmp",
      "cgmp",
      "fda",
      "apqr",
      "qms",
      "validation protocol",
      "21 cfr",
      "sop",
      "biosimilars",
      "hplc",
      "gc",
      "karl fischer",
      "chromatogram",
      "dissolution",
      // other
      "garment",
      "textile",
      "fabric",
      "merchandiser",
      "vendor location",
      "inline inspection",
      "final inspection",
      "production quality",
      "sample evaluation",
      "risk analysis",
      "buyer requirements",
      "raw materials",
      "export house",
      "retail quality",
      "pattern measuring",
      "accessories inspection",
      "measurement review",
      "non-conformity",
      "factory quality",
      "production approvals",
      "quality communication",
      "footwear",
      "shoe",
      "leather",
      "fabric",
      "textile",
      "garment",
      "apparel",
      "stitching",
      "cutting",
      "manufacturing plant",
      "factory",
      "production line",
      "assembly line",
      "puf panel",
      "steel",
      "audit",
      "inspector",
      "quality control executive",
      "qc executive",
      "measurement",
      "calibration",
      "inventory",
      "warehouse",
      "logistics",
      "supply chain",
      "shrinking",
      "scrap",
      "wastage",
      "batch record",
      "production manager",
      "retail",
      "store manager",
      "shift manager",
      "floor manager",
      "showroom",
      "inventory management",
      "stock",
      "visual merchandising",
      "cashier",
      "guest experience",
      "hospitality",
      "hostel",
      "housekeeping",
      "front desk",
      "food and beverage",
      "kitchen",
      "restaurant",
      "tax",
      "audit",
      "statutory",
      "compliance",
      "payroll",
      "accounting",
      "chartered accountant",
      "gst",
      "returns",
      "reconciliation",
      "journal entries",
      "chargeback",
      "dispute",
      "inbound",
      "outbound",
      "collections",
      "kyc",
      "marketing",
      "campaign",
      "brand awareness",
      "customer retention",
      "crm channel",
      "email marketing",
      "whatsapp marketing",
      "seo",
      "sem",
      "content writing",
      "social media",
      "lead generation",
      "sales",
      "hse",
      "health safety",
      "environment",
      "production planning",
      "manufacturing methods",
      "plant manager",
      "assembly",
      "plc",
      "scada",
      "hmi",
      "siemens",
      "mitsubishi",
      "allen bradley",
      "control panel",
      "wiring",
      "drive commissioning",
      "quality inspector",
      "certified asnt",
      "nc management",
      "ndt techniques",
      "engineering drawings",
      "vfd",
      "switchgear",
      "substation",
      "grid automation",
      "power system",
      "hydraulics",
      "pneumatics",
      "turbine",
      "locomotive",
      "train control",
      "braking system",
      "territory sales",
      "sales in charge",
      "distributor",
      "wholesaler",
      "fmcg",
      "retailer",
      "plan-o-gram",
      "merchandising",
      "beat plan",
      "secondary sales",
      "primary sales",
      "dealer",
      "consumer complaints",
      "fulfillment center",
      "process associate",
      "picking",
      "packing",
      "kaizen",
      "shop floor",
      "inventory count",
      "shift management",
      "content management",
      "cms",
      "seo",
      "search engine optimization",
      "copywriting",
      "proofreading",
      "marketing",
      "brand voice",
      "creative writing",
      "catalogue manager",
      "adobe experience manager",
      "magento",
      "wordpress",
      "sheet metal",
      "welding",
      "fabrication",
      "powder coating",
      "electro plating",
      "calibration",
      "gauge",
      "vernier",
      "micrometer",
      "hvac",
      "piping",
      "nema",
      "din",
      "astm",
      "panel manufacturing",
      "switchboard",
      "construction industry",
      "architectural works",
      "job safety environmental analysis",
      "construction",
      "procure-to-pay processes",
      "order-to-cash lifecycle",
      "iso 9001",
      "iso 9001:2015",
      "iso 14001",
      "ohsas 18001",
      "stages of manufacturing",
      "laboratory skills",
      "laboratory testing",
      "cnc programmers",
      "first article inspection",
      "inspection checklists",
      "cmm reports",
      "cad models",
      "inspection drawings",
      "turbine blades",
      "precision manufacturing",
      "standard work instructions",
      "forging",
      "aluminium",
      "metallurgical properties",
      "inspection gauges",
      "alloys",
      "ppap audit",
      "production process",
      "electrical",
      "complex manufacturing",
      "civil engineering",
      "construction management",
      "thermal power plant",
      "high-rise building",
      "creative head",
      "creative or design leadership",
      "design engagements",
      "storytelling",
      "guide designers",
      "high-stakes presentations",
      "refinery",
      "crude",
      "feedstocks",
    ],
  },

  HardwareQA: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "hardware test",
      "validation engineer",
      "system validation",
      "silicon validation",
      "post-silicon",
      "pre-silicon",
      "forging",
      "board bring-up",
      "manufacturing test",
      "aluminium forging",
      "complex manufacturing",
      "equipment specification and qualification",
      "equipment qualification",
      "nonferrous",
      "precision manufacturing",
      "power integrity",
      "mechanical engineer",
      "mechanical design engineer",
      "electric motor",
      "electric vehicle",
      "manufacturing drawings",
      "bill of materials",
      "component development",
      "industrial manufacturing",
      "geometric dimensioning",
      "gd&t",
      "manufacturing processes",
      "additive manufacturing",
      "aluminum die casting",
      "plastic injection moulding",
      "control system engineer",
      "instrumentation engineer",
      "mechanical design",
      "electrical engineer",
      "industrial automation",
      "plc programmer",
      "scada engineer",
      "hmi developer",
      "finite element analysis",
      "computational fluid dynamics",
      "quality control engineer",
      "panel design",
      "switchgear",
      "instrumentation engineer",
      "electrical panel",
      "production process",
      "electrical and programming",
      "material & labor costs",
      "asic verification",
      "soc verification",
      "uvm methodology",
      "constrained random verification",
      "design verification",
    ],
    terms: [
      "hardware",
      "pcb",
      "rtl",
      "fpga",
      "asic",
      "embedded",
      "firmware",
      "board design",
      "schematic",
      "layout",
      "lab",
      "oscilloscope",
      "signal integrity",
      "logic analyzer",
      "spectrum analyzer",
      "jtag",
      "assembly line",
      "debugger",
      "multimeter",
      "test fixture",
      "electrical",
      "bench testing",
      "emc",
      "emi",
      "mechatronics",
      "electromechanical",
      "3d cad",
      "sensors",
      "valves",
      "fmea",
      "prototypes",
      "emotor",
      "automotive",
      "drivetrain",
      "casting",
      "machining",
      "stamping",
      "catia",
      "ansys",
      "plc",
      "scada",
      "hmi",
      "vfd",
      "dcs",
      "modbus",
      "profibus",
      "profinet",
      "omron",
      "fanuc",
      "kuka",
      "catia",
      "solidworks",
      "creo",
      "nx",
      "autocad",
      "ansys",
      "abaqus",
      "bom",
      "gd&t",
      "hydraulics",
      "pneumatics",
      "switchgear",
      "substation",
      "locomotive",
      "powertrain",
      "engine",
      "chassis",
      "hvac",
      "plc",
      "scada",
      "hmi",
      "dcs",
      "sheet metal",
      "welding",
      "fabrication",
      "moulding",
      "casting",
      "iso 9001",
      "nema",
      "ul",
      "ce",
      "iec",
      "calibration",
      "inspection",
      "incoming material",
      "Verilog",
      "systemverilog",
      "uvm",
      "pcie",
      "pci express",
      "cxl",
      "interconnect",
      "simulation",
      "debug",
    ],
    negative: [
      // Software/web
      "web",
      "frontend",
      "backend",
      "microservices",
      "ui",
      "api testing",
      "react",
      "node.js",
      "javascript",
      "css",
      "html",
      "java",
      "c#",
      "full stack",
      // Cloud/devops
      "cloud",
      "aws",
      "gcp",
      "azure",
      "devops",
      "sre",
      "ci/cd",
      // Non-relevant
      "mep",
      "civil",
      "construction",
      "plumbing",
      "talent acquisition",
      "recruitment",
      "hiring",
      "product roadmap",
      "stakeholder management",
      "etl",
      "data lake",
      // Pharma
      "apqr",
      "biosimilars",
      "oos",
      "21 cfr",
      "batch record",
      "vmp",
      "selenium",
      "cypress",
      "playwright",
      "rest assured",
      "java",
      "python",
      "react",
      "angular",
      "aws",
      "azure",
      "cloud",
      "saas",
      "web application",
      "selenium",
      "cypress",
      "java",
      "python",
      "react",
      "content management",
    ],
  },

  PharmaQA: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "quality management system",
      "gmp compliance",
      "process validation",
      "computer system validation",
      "apqr",
      "quality oversight",
      "regulatory audits",
      "batch record review",
      "corrective and preventive action",
      "change control management",
      "quality control for pharma",
      "inspection readiness",
      "validation protocol and report",
      "quality operations and gmp",
      "biosimilar operations",
      "system compliance",
      "design control quality management",
      "analytical method validation",
      "impurity profiling",
      "release testing",
    ],
    terms: [
      "qms",
      "gmp",
      "cgmp",
      "fda",
      "ema",
      "oos",
      "oot",
      "capa",
      "apqr",
      "validation",
      "protocol",
      "report",
      "tpms", // Third-Party Manufacturers
      "biosimilars",
      "pharmaceutical",
      "biotech",
      "medical device",
      "audit",
      "inspection",
      "deviation",
      "change control",
      "batch processing",
      "sop",
      "bpr", // Batch Production Record / Batch Processing Record
      "bmr", // Batch Manufacturing Record
      "dcs", // Document Control System
      "ensur", // Specific system name (ENSUR 4.2)
      "iso13485",
      "eumdd",
      "iec 62304",
      "21 cfr part",
      "vmp", // Validation Master Plan
      "csv", // Computer System Validation
      "iq", // Installation Qualification
      "oq", // Operational Qualification
      "pq", // Performance Qualification
      "risk assessment",
      "quality review",
      "hplc",
      "pharma",
      "hipaa",
      "argus safety",
      "health science",
      "gc",
      "uv",
      "ir",
      "karl fischer",
      "lmis",
      "cds",
      "chromatogram",
    ],
    negative: [
      // Exclude generic SoftwareQA terms unless paired with Pharma terms
      "selenium",
      "cypress",
      "python",
      "javascript",
      "java",
      "ui testing",
      "api testing",
      "sdet",
      // Exclude pure HardwareQA/Engineering terms
      "pcb",
      "rtl",
      "fpga",
      "mechanical",
      "electromechanical",
      "3d cad",
      // Exclude generic IT roles (unless compliance/validation)
      "full stack",
      "backend",
      "frontend",
      "microservices",
      "devops",
      "sre",
      "kubernetes",
    ],
  },

  "DevOps/SRE": {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "site reliability",
      "platform engineer",
      "infrastructure engineer",
      "service mesh",
      "infrastructure as code",
      "platform as code",
      "incident management",
      "high availability",
      "disaster recovery",
      "production engineer",
      "production support",
      "technical operations",
      "it operations",
      "system administrator",
    ],
    terms: [
      "devops",
      "sre",
      "reliability engineer",
      "cloud engineer",
      "kubernetes",
      "k8s",
      "docker",
      "helm",
      "terraform",
      "ansible",
      "puppet",
      "chef",
      "saltstack",
      "container",
      "ci/cd",
      "github actions",
      "jenkins",
      "gitlab ci",
      "circleci",
      "travis ci",
      "prometheus",
      "grafana",
      "observability",
      "pagerduty",
      "datadog",
      "cloudwatch",
      "splunk",
      "elk",
      "elasticsearch",
      "logstash",
      "kibana",
      "new relic",
      "cloud",
      "aws",
      "gcp",
      "azure",
      "istio",
      "envoy",
      "on-call",
      "incident",
      "postmortem",
      "iac",
      "automation",
      "scripting",
      "bash",
      "powershell",
      "slo",
      "sli",
      "sla",
      "scalability",
      "monitoring",
      "logging",
      "alerting",
      "linux",
      "unix",
      "shell",
      "tomcat",
      "apache",
      "iis",
      "ssl",
      "tls",
      "certificate",
      "pki",
    ],
    negative: [
      "manual testing",
      "test case",
      "ui automation",
      "qa",
      "quality assurance",
      "sdet",
      "test plan",
      "bug report",
      "selenium",
      "cypress",
      "frontend",
      "react",
      "angular",
      "vue",
      "ui/ux",
      "application developer",
      "hardware",
      "pcb",
      "fpga",
      "embedded",
      "firmware",
      "oscilloscope",
      "rtl",
      "talent acquisition",
      "recruitment",
      "hiring",
      "sourcing candidates",
      "offer letter",
      "compensation",
      "civil",
      "construction",
      "mep",
      "automotive",
      "mechanical",
      "product strategy",
      "business analyst",
      "scrum master",
      "tableau",
      "procurement",
      "vendor management",
      "supplier",
      "supply chain",
      "manufacturing",
      "factory",
      "plant",
      "assembly line",
      "call center",
      "bpo",
      "voice process",
    ],
  },

  DataEngg: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "data engineer",
      "etl developer",
      "data pipeline",
      "data warehousing",
      "business intelligence",
      "big data",
      "data modeling",
      "data governance",
      "data quality assurance",
      "master data management",
      "analytics engineer",
    ],
    terms: [
      "spark",
      "hadoop",
      "hive",
      "kafka",
      "airflow",
      "etl",
      "elt",
      "data lake",
      "databricks",
      "dbt",
      "tableau",
      "power bi",
      "qlik",
      "snowflake",
      "redshift",
      "dynamodb",
      "bigquery",
      "nosql",
      "ssis",
      "ssas",
      "ssrs",
      "data vault",
      "fivetran",
      "stitch",
      "glue",
      "lakehouse",
    ],
    negative: [
      "frontend",
      "ui",
      "ux",
      "react",
      "angular",
      "vue",
      "mobile",
      "qa",
      "tester",
      "sdet",
      "manual testing",
      "firmware",
      "hardware",
      "pcb",
      "fpga",
      "oscilloscope",
      "mechanical",
      "incident management",
      "on-call",
      "kubernetes",
      "scrum master",
      "product roadmap",
      "stakeholder",
      "systemverilog",
      "asic",
      "rtl",
      "fpga",
      "hardware",
      "oscilloscope",
      "silicon",
      "post-silicon",
      "pcie",
      "interconnect",
      "physical layer",
    ],
  },

  "ML/AI": {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "data scientist",
      "machine learning scientist",
      "applied scientist",
      "ml engineer",
      "ml research",
      "research scientist",
      "computer vision",
      "natural language processing",
      "nlp",
      "recommendation systems",
      "time series forecasting",
      "experiment design",
      "ab testing",
      "data associate",
      "data annotation",
      "data labeling",
      "ground truth",
      "human in the loop",
      "logistic regression",
      "random forest",
      "decision tree",
      "credit risk analytics",
      "scorecard development",
    ],
    terms: [
      "ml",
      "ai",
      "llm",
      "genai",
      "rag",
      "prompt engineering",
      "feature engineering",
      "model training",
      "model evaluation",
      "model tuning",
      "hyperparameter",
      "pytorch",
      "tensorflow",
      "sklearn",
      "xgboost",
      "lightgbm",
      "huggingface",
      "vector db",
      "faiss",
      "milvus",
      "weaviate",
      "sagemaker",
      "bedrock",
      "comet",
      "wandb",
      "mlflow",
      "notebook",
      "statistics",
      "bayesian",
      "regression",
      "classification",
      "clustering",
      "experiment tracking",
      "offline evaluation",
      "online metrics",
      "annotation",
      "labeling",
      "labelbox",
      "scale ai",
      "sagemaker ground truth",
      "artificial general intelligence",
      "linguistics",
      "speech recognition",
      "SAS",
      "SQL",
      "PowerBI",
      "Tableau",
    ],
    negative: [
      "test case",
      "manual testing",
      "qa",
      "tester",
      "on-call",
      "incident",
      // DevOps
      "jenkins",
      "terraform",
      "kubernetes",
      "pcb",
      "rtl",
      "fpga",
      // Hardware
      "oscilloscope",
      "talent acquisition",
      "recruitment",
      "hiring",
      "product roadmap",
      "stakeholder management",
    ],
  },

  Security: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "security engineer",
      "application security",
      "cloud security",
      "product security",
      "security analyst",
      "security operations",
      "soc analyst",
      "penetration testing",
      "red team",
      "blue team",
      "threat detection",
      "security architecture",
      "identity and access management",
      "iam",
      "governance risk compliance",
      "grc",
      "risk management",
      "vulnerability management",
      "terminal security",
      "security operations",
      "access control and key management",
      "mock drills",
      "vvip movement",
      "threat intelligence",
      "incident response",
      "zero trust",
      "network security",
    ],
    terms: [
      "infosec",
      "appsec",
      "secops",
      "siem",
      "soar",
      "splunk",
      "qrader",
      "sentinel",
      "crowdstrike",
      "okta",
      "auth0",
      "sso",
      "mfa",
      "oidc",
      "oauth",
      "nist",
      "iso 27001",
      "soc2",
      "pci-dss",
      "hipaa",
      "gdpr",
      "burp",
      "zap",
      "nessus",
      "qualys",
      "osint",
      "mitre att&ck",
      "owasp",
      "secrets scanning",
      "sast",
      "dast",
      "sca",
      "key management",
      "access control",
      "biometric",
      "concessionaires",
      "firewall",
      "endpoint",
    ],
    negative: [
      "qa",
      "tester",
      "manual testing",
      "frontend",
      "react",
      "angular",
      "vue",
      "pcb",
      "fpga",
      "oscilloscope",
      "etl",
      "data warehousing",
      "scrum master",
      "product manager",
    ],
  },

  RPA: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "rpa developer",
      "uipath developer",
      "automation anywhere developer",
      "blue prism developer",
      "robotic process automation",
      "attended automation",
      "unattended automation",
      "UiPath Orchestrator",
      "UiPath Studio",
      "UiPath Assistant",
      "UiPath ReFramework",
      "UiPath Document Understanding",
      "UiPath AI Center",
      "UiPath Action Center",
      "UiPath Insights",
      "UiPath Governance",
      "UiPath Deployment",
      "UiPath Licensing",
      "UiPath Queue Management",
      "UiPath Trigger Management",
      "UiPath Asset Management",
      "UiPath Package Deployment",
      "UiPath Marketplace",
      "intelligent automation",
      "hyperautomation",
      "automation center of excellence",
      "coe lead",
      "delivery director",
      "automation delivery",
      "power platform",
      "low code",
      "no code",
    ],
    terms: [
      "uipath",
      "automation anywhere",
      "blue prism",
      "orchestrator",
      "reframework",
      "workflow analyzer",
      "invoke workflow",
      "custom activity",
      "robot provisioning",
      "package publishing",
      "transaction item",
      "queue trigger",
      "automation hub",
      "document understanding",
      "ocr engines",
      "ai fabric",
      "action center",
      "insights dashboard",
      "blueprism",
      "automation anywhere",
      "power automate",
      "workfusion",
      "pega",
      "nice",
      "co-pilot",
    ],
    negative: [
      "qa",
      "test case",
      "manual testing",
      "kubernetes",
      "terraform",
      "jenkins",
      "pcb",
      "rtl",
      "fpga",
      // Physical/Aviation Security / Airport Ops
      "immigration",
      "customs",
      "airport",
      "terminal",
      "igia",
      "skytrax",
      "security operations",
      "key management",
      "access control",
      "biometric access",
      "mock drills",
      "vvip",
      "touting",
      "concessionaires",
      "house keeping agencies",
      // Cyber/DevOps terms
      "kubernetes",
      "terraform",
      "prometheus",
      "grafana",
      // QA specific test frameworks
      "selenium",
      "cypress",
      "postman",
      "api testing",
      "test case",
      "sdet",
      "recruitment",
      "talent acquisition",
      "hiring",
    ],
  },

  DBA: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "database administrator",
      "database reliability engineer",
      "performance tuning",
      "backup and recovery",
      "disaster recovery",
      "replication",
      "high availability",
    ],
    terms: [
      "oracle dba",
      "sql server dba",
      "mysql dba",
      "postgres dba",
      "pl/sql",
      "t-sql",
      "indexing",
      "query tuning",
      "partitioning",
      "rds",
      "aurora",
      "exadata",
      "asm",
      "golden gate",
      "logical replication",
    ],
    negative: [
      "etl",
      "spark",
      "airflow",
      "kubernetes",
      "terraform",
      "selenium",
      "cypress",
      "pcb",
      "rtl",
    ],
  },

  Management: {
    weight: 1,
    titleBoost: 1.8,
    phrases: [
      "product manager",
      "project manager",
      "scrum master",
      "agile coach",
      "product owner",
      "business analyst",
      "product strategy",
      "product roadmap",
      "stakeholder management",
      "user stories",
      "requirements gathering",
      "go-to-market",
      "pmp certified",
      "program manager",
      "delivery manager",
      "delivery director",
      "practice head",
      "cluster manager",
      "regional manager",
      "country head",
      "segment head",
      "engineering manager",
      "operations manager",
      "delivery head",
      "practice lead",
      "general manager",
      "business partner",
      "strategic alignment",
      "pmo teams",
      "it initiatives",
      "functional domain",
      "technology decisions",
    ],

    terms: [
      "agile",
      "scrum",
      "kanban",
      "pmp",
      "csm",
      "jira",
      "confluence",
      "trello",
      "wbs",
      "budgeting",
      "timeline",
      "risk management",
      "stakeholder",
      "feature",
      "release",
      "mvp",
      "okr",
      "kpi",
      "gantt",
      "project",
      "product",
      "management",
      "stakeholder",
      "analyst",
      "ux research",
      "market research",
      "roadmap",
      "portfolio",
      "p&l",
      "profit and loss",
      "revenue",
      "budget",
      "forecast",
      "audit",
      "compliance",
      "sop",
      "roster",
      "scheduling",
      "kpi",
      "sla",
      "p&l",
      "budget",
      "strategy",
      "roadmap",
      "tender",
      "bidding",
      "resource planning",
      "headcount",
      "capex",
      "opex",
      "business development",
      "stakeholder",
      "kpi",
      "risk management",
    ],
    negative: [
      "coding",
      "javascript",
      "python",
      "java",
      "c#",
      "sql",
      "api development",
      "full stack",
      "backend",
      "frontend",
      "developer",
      "engineer",
      "qa",
      "tester",
      "sdet",
      "manual testing",
      "automation",
      "kubernetes",
      "terraform",
      "devops",
      "sre",
      "hardware",
      "pcb",
      "rtl",
      "firmware",
      "procurement",
      "vendor management",
      "supplier",
      "supply chain",
      "bpo",
      "kpo",
      "call center",
      "insurance process",
      "claims processing",
      "inbound",
      "outbound",
      "voice process",
      "non-voice",
      "process associate",
      "operations executive",
      "shrinkage",
      "attrition",
      "sla management",
      "content writing",
      "seo",
    ],
  },

  HR: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "human resources",
      "talent acquisition",
      "employee relations",
      "talent management",
      "people and culture",
      "talent acquisition",
      "sourcing",
      "hiring",
      "screening",
    ],
    terms: [
      "recruiter",
      "payroll",
      "onboarding",
      "hiring",
      "shrm",
      "hris",
      "compensation",
      "recruit",
      "sourcing",
      "screening",
      "talent",
      "hiring",
    ],
    negative: [
      "technical lead",
      "developer",
      "coding",
      "technical architect",
      "scrum master",
    ],
  },

  Finance: {
    weight: 1,
    titleBoost: 1.6,
    phrases: [
      "chartered accountant",
      "financial analyst",
      "accounts payable",
      "accounts receivable",
      "profit and loss",
    ],
    terms: [
      "accounting",
      "audit",
      "taxation",
      "ledger",
      "cpa",
      "budgeting",
      "treasury",
      "tally",
    ],
    negative: [
      "fintech developer",
      "software engineer",
      "data scientist",
      "developer",
      "coding",
      "programming",
      "site reliability",
      "platform engineer",
      "infrastructure engineer",
      "service mesh",
      "infrastructure as code",
      "platform as code",
      "incident management",
      "high availability",
      "disaster recovery",
      "production engineer",
      "production support",
      "technical operations",
      "it operations",
      "system administrator",
    ],
  },

  Marketing: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "digital marketing",
      "content strategy",
      "social media manager",
      "brand awareness",
      "growth hacking",
    ],
    terms: [
      "seo",
      "sem",
      "campaign",
      "copywriter",
      "advertising",
      "branding",
      "leads",
      "market",
    ],
    negative: ["marketing analytics engineer", "data engineer"],
  },

  Sales: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "business development",
      "account executive",
      "inside sales",
      "sales development",
    ],
    terms: [
      "crm",
      "salesforce",
      "quota",
      "outreach",
      "prospecting",
      "negotiation",
      "targets",
    ],
    negative: ["salesforce developer", "technical sales engineer"],
  },

  Legal: {
    weight: 1,
    titleBoost: 1.7,
    phrases: [
      "legal counsel",
      "corporate lawyer",
      "regulatory compliance",
      "contract management",
    ],
    terms: [
      "paralegal",
      "litigation",
      "attorney",
      "compliance",
      "policy",
      "ethics",
      "arbitration",
    ],
    negative: ["it compliance", "security auditor"],
  },

  CustomerSupport: {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "customer success",
      "technical support",
      "client relations",
      "customer experience",
      "call center",
      "help desk",
      "customer service",
    ],
    terms: [
      "helpdesk",
      "ticketing",
      "zendesk",
      "support",
      "troubleshooting",
      "escalation",
      "voice",
      "chat",
    ],
    negative: ["software engineer", "development"],
  },
  Manufacturing: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "production planning",
      "plant management",
      "assembly line",
      "shop floor",
      "quality control",
      "health and safety",
    ],
    terms: [
      "factory",
      "machining",
      "iso",
      "six sigma", // Also used in IndustrialEngg
      "ehs",
      "maintenance",
      "operator",
      "welder",
      "fabrication",
    ],
    negative: ["software", "web development", "coding"],
  },

  Retail: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "store operations",
      "visual merchandising",
      "inventory management",
      "customer service",
      "point of sale",
    ],
    terms: [
      "retail",
      "pos",
      "showroom",
      "cashier",
      "billing",
      "stock",
      "merchandise",
      "fmcg", // Fast Moving Consumer Goods
    ],
    negative: ["backend", "manufacturing plant", "heavy machinery"],
  },

  Logistics: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "supply chain management",
      "warehouse operations",
      "last mile delivery",
      "freight forwarding",
    ],
    terms: [
      "logistics",
      "shipping",
      "fleet",
      "3pl",
      "cargo",
      "inventory",
      "scm",
      "courier",
    ],
    negative: ["software developer", "ux design"],
  },
};

// --- General Color Palette (for Company/Location) ---
export const GENERAL_COLOR_PALETTE = [
  { bg: "rgba(54, 162, 235, 0.7)" }, // Blue
  { bg: "rgba(255, 99, 132, 0.7)" }, // Red
  { bg: "rgba(75, 192, 192, 0.7)" }, // Green
  { bg: "rgba(153, 102, 255, 0.7)" }, // Purple
  { bg: "rgba(255, 159, 64, 0.7)" }, // Orange
  { bg: "rgba(255, 206, 86, 0.7)" }, // Yellow
  { bg: "rgba(201, 203, 207, 0.7)" }, // Grey
  { bg: "rgba(255, 0, 255, 0.7)" }, // Magenta
  { bg: "rgba(0, 255, 0, 0.7)" }, // Lime Green
  { bg: "rgba(128, 0, 0, 0.7)" }, // Maroon
  { bg: "rgba(0, 128, 128, 0.7)" }, // Teal
  { bg: "rgba(0, 0, 128, 0.7)" }, // Navy Blue
  { bg: "rgba(128, 128, 0, 0.7)" }, // Olive
  { bg: "rgba(128, 0, 128, 0.7)" }, // Plum/Dark Magenta
  { bg: "rgba(255, 105, 180, 0.7)" }, // Hot Pink
  { bg: "rgba(255, 215, 0, 0.7)" }, // Gold
  { bg: "rgba(173, 216, 230, 0.7)" }, // Light Blue
  { bg: "rgba(240, 128, 128, 0.7)" }, // Light Coral
  { bg: "rgba(144, 238, 144, 0.7)" }, // Light Green
  { bg: "rgba(238, 130, 238, 0.7)" }, // Violet
  { bg: "rgba(112, 128, 144, 0.7)" }, // Slate Grey
  { bg: "rgba(189, 183, 107, 0.7)" }, // Dark Khaki
  { bg: "rgba(255, 182, 193, 0.7)" }, // Light Pink
  { bg: "rgba(255, 228, 181, 0.7)" }, // Moccasin
  { bg: "rgba(100, 149, 237, 0.7)" }, // Cornflower Blue
  { bg: "rgba(255, 99, 71, 0.7)" }, // Tomato
  { bg: "rgba(60, 179, 113, 0.7)" }, // Medium Sea Green
  { bg: "rgba(72, 61, 139, 0.7)" }, // Dark Slate Blue
];

// --- Semantic Role Type Colors (for byRoleType) ---
export const ROLE_TYPE_COLOR_PALETTE = {
  SoftwareDEV: { bg: "rgba(54, 162, 235, 0.7)" }, // Blue
  SoftwareQA: { bg: "rgba(75, 192, 192, 0.7)" }, // Green
  Management: { bg: "rgba(255, 99, 132, 0.7)" }, // Red
  "ML/AI": { bg: "rgba(153, 102, 255, 0.7)" }, // Purple
  "DevOps/SRE": { bg: "rgba(255, 159, 64, 0.7)" }, // Orange
  DataEngg: { bg: "rgba(255, 206, 86, 0.7)" }, // Yellow
  HardwareQA: { bg: "rgba(0, 128, 128, 0.7)" }, // Teal
  PharmaQA: { bg: "rgba(60, 179, 113, 0.7)" }, // Medium Sea Green
  Security: { bg: "rgba(128, 0, 0, 0.7)" }, // Maroon
  RPA: { bg: "rgba(100, 149, 237, 0.7)" }, // Cornflower Blue
  DBA: { bg: "rgba(100, 136, 172, 0.7)" }, // Slate Grey
  Default: { bg: "rgba(201, 203, 207, 0.7)" }, // Grey (kept as default)
};

export const WORD_TO_NUM = {
  zero: 0,
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  eleven: 11,
  twelve: 12,
  thirteen: 13,
  fourteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  nineteen: 19,
  twenty: 20,
};

// Role-defining title nudges only (specific > generic). Order matters.
export const TITLE_NUDGES = [
  {
    regex: /\b(full\s*stack|fullstack|web\s*application\s*developer)\b/i,
    cat: "SoftwareDEV",
    boost: 4,
  },
  // --- SoftwareQA ---
  {
    regex: /\b(sdet|software\s*developer\s*in\s*test)\b/i,
    cat: "SoftwareQA",
    boost: 5,
  },
  {
    regex:
      /\b(qa\s*engineer|quality\s*engineer|test\s*automation|automation\s*tester)\b/i,
    cat: "SoftwareQA",
    boost: 4,
  },
  {
    regex: /\b(test\s*architect|qa\s*architect)\b/i,
    cat: "SoftwareQA",
    boost: 3,
  },

  // --- DevOps / SRE / Platform (infra) ---
  {
    regex: /\b(sre|site\s*reliability\s*engineer)\b/i,
    cat: "DevOps/SRE",
    boost: 5,
  },
  {
    regex:
      /\b(devops|platform\s*engineer|production\s*engineer|infrastructure\s*engineer)\b/i,
    cat: "DevOps/SRE",
    boost: 4,
  },

  // --- HardwareQA / Embedded / Silicon / Mechanical ---
  {
    regex:
      /\b(manufacturing|quality\scontrol|asic|fpga|rtl|post-?silicon|pre-?silicon|silicon\s*validation)\b/i,
    cat: "HardwareQA",
    boost: 5,
  },
  {
    regex:
      /\b(hardware|embedded|firmware|validation\s*engineer|mechatronics|electro-?mechanical|mechanical)\b/i,
    cat: "HardwareQA",
    boost: 4,
  },
  {
    regex: /\b(design\s*verification|dv\s*engineer|verification\s*engineer)\b/i,
    cat: "HardwareQA",
    boost: 5,
  },
  // --- Data Engineering / Analytics Engineering ---
  {
    regex:
      /\b(data\s*engineer|analytics\s*engineer|data\s*platform\s*engineer)\b/i,
    cat: "DataEngg",
    boost: 4,
  },
  {
    regex: /\b(etl\s*developer|data\s*architect)\b/i,
    cat: "DataEngg",
    boost: 3,
  },

  // --- Data Science / ML ---
  {
    regex: /\b(data\s*scientist|applied\s*scientist|research\s*scientist)\b/i,
    cat: "ML/AI",
    boost: 4,
  },
  {
    regex:
      /\b(risk\s*analyst|analytics\s*manager|data\s*scientist\s*-\s*banking|credit\s*risk)\b/i,
    cat: "ML/AI",
    boost: 5,
  },
  // Ambiguous but useful signal; let description/keyword scoring finalize
  {
    regex:
      /\b(ml\s*engineer|machine\s*learning\s*engineer|computer\s*vision|nlp)\b/i,
    cat: "ML/AI",
    boost: 3,
  },

  // --- Security / InfoSec ---
  {
    regex:
      /\b(application\s*security|appsec|security\s*engineer|product\s*security|cloud\s*security)\b/i,
    cat: "Security",
    boost: 4,
  },
  {
    regex:
      /\b(soc\s*analyst|penetration\s*tester|red\s*team|blue\s*team|grc|governance\s*risk\s*compliance|iam)\b/i,
    cat: "Security",
    boost: 4,
  },

  // --- RPA / UiPath ---
  {
    regex:
      /\b(rpa\s*developer|uipath\s*developer|automation\s*anywhere\s*developer|blue\s*prism\s*developer|rpa\s*engineer)\b/i,
    cat: "RPA",
    boost: 5,
  },
  {
    regex: /\b(re-framework|robotic\s*process\s*automation)\b/i,
    cat: "RPA",
    boost: 4,
  },

  // --- DBA ---
  {
    regex:
      /\b(database\s*administrator|dba|database\s*reliability\s*engineer)\b/i,
    cat: "DBA",
    boost: 5,
  },
  {
    regex: /\b(oracle\s*dba|sql\s*server\s*dba|postgres\s*dba|mysql\s*dba)\b/i,
    cat: "DBA",
    boost: 5,
  },

  // --- Management / PM / Program / Scrum ---
  {
    regex:
      /\b(product\s*manager|project\s*manager|program\s*manager|delivery\s*manager|product\s*owner|scrum\s*master|agile\s*coach)\b/i,
    cat: "Management",
    boost: 5,
  },

  // --- Pharma QA ---
  {
    regex: /\b(computer\s*system\s*validation|csv)\b/i,
    cat: "PharmaQA",
    boost: 5,
  },
  {
    regex: /\b(gxp|cgmp|gmp)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(quality\s*management\s*system|qms)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(pharma\s*quality|medical\s*device\s*qa|biotech\s*qa)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(validation\s*specialist|validation\s*scientist)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex:
      /\b(regulatory\s*compliance|inspection\s*readiness|quality\s*auditor)\b/i,
    cat: "PharmaQA",
    boost: 3,
  },
  {
    regex: /\b(capa|apqr|change\s*control)\b/i,
    cat: "PharmaQA",
    boost: 3,
  },
  // --- Manufacturing ---
  {
    regex:
      /\b(plant\s*head|factory\s*manager|production\s*supervisor|quality\s*inspector)\b/i,
    cat: "Manufacturing",
    boost: 5,
  },

  // --- Retail ---
  {
    regex: /\b(store\s*manager|retail\s*associate|cashier|floor\s*manager)\b/i,
    cat: "Retail",
    boost: 5,
  },

  // --- Logistics ---
  {
    regex:
      /\b(warehouse\s*manager|logistics\s*coordinator|fleet\s*supervisor|delivery\s*partner)\b/i,
    cat: "Logistics",
    boost: 5,
  },
  // --- HR ---
  {
    regex: /\b(hr\s*manager|recruiter|talent\s*partner)\b/i,
    cat: "HR",
    boost: 5,
  },

  // --- Finance ---
  {
    regex: /\b(accountant|finance\s*manager|controller|tax\s*specialist)\b/i,
    cat: "Finance",
    boost: 5,
  },

  // --- Marketing/Sales ---
  {
    regex: /\b(sales\s*manager|bde|account\s*manager)\b/i,
    cat: "Sales",
    boost: 4,
  },
  {
    regex: /\b(marketing\s*specialist|seo\s*analyst|content\s*writer)\b/i,
    cat: "Marketing",
    boost: 4,
  },

  // --- Legal ---
  {
    regex: /\b(legal|lawyer|compliance\s*officer|counsel)\b/i,
    cat: "Legal",
    boost: 5,
  },
];

export const CITY_ALIAS = {
  bengaluru: [
    "bangalore",
    "bangalore urban",
    "bengaluru, karnataka",
    "bangalore, karnataka",
    "bengaluru, karnataka, india",
    "bangalore, karnataka, india",
    "bengaluru, india",
    "bangalore, india",
    "greater bangalore area",
    "bengaluru area",
    "bangalore area",
    "bengaluru metropolitan region",
    "bangalore metropolitan region",
    "bengaluru east",
    "bengaluru south",
    "electronic city",
    "whitefield",
    "devanahalli",
    "hosur",
    "kolar",
    "ramanagara",
    "tumkur",
    "greater bengaluru area",
  ],
  mumbai: [
    "bombay",
    "mumbai, maharashtra",
    "bombay, maharashtra",
    "mumbai, maharashtra, india",
    "bombay, maharashtra, india",
    "mumbai, india",
    "bombay, india",
    "greater mumbai area",
    "mumbai area",
    "mumbai metropolitan region",
    "mmr",
    "navi mumbai",
    "thane",
    "alibag",
    "khandala",
    "palghar",
    "panvel",
    "sion",
    "ulhasnagar",
  ],
  delhi: [
    "new delhi",
    "delhi ncr",
    "delhi-ncr",
    "ncr",
    "national capital region",
    "national capital region (ncr)",
    "delhi, delhi",
    "new delhi, delhi",
    "delhi, india",
    "new delhi, india",
    "greater delhi area",
    "delhi area",
    "delhi metropolitan area",
  ],
  gurgaon: [
    "gurugram",
    "gurgaon, haryana",
    "gurugram, haryana",
    "gurgaon, haryana, india",
    "gurugram, haryana, india",
    "gurgaon, india",
    "gurugram, india",
    "gurgaon area",
    "gurugram area",
    "gurgaon ncr",
    "gurugram ncr",
    "nuh",
  ],
  noida: [
    "noida, uttar pradesh",
    "noida, uttar pradesh, india",
    "noida, u.p.",
    "noida, up",
    "noida, india",
    "greater noida",
    "greater noida, uttar pradesh",
    "noida extension",
    "noida area",
    "noida ncr",
    "gautam buddha nagar",
  ],
  hyderabad: [
    "hyderabad, telangana",
    "hyderabad, telangana, india",
    "hyderabad, india",
    "greater hyderabad area",
    "hyderabad metropolitan area",
    "hyderabad area",
    "secunderabad",
    "hyderabad/secunderabad",
    "cyberabad",
    "serilingampalli",
  ],
  pune: [
    "pune, maharashtra",
    "pune, maharashtra, india",
    "pune, india",
    "greater pune area",
    "pune area",
    "pune metropolitan region",
    "pmr",
    "hinjewadi",
    "pimpri-chinchwad",
    "pune/pimpri-chinchwad area",
    "chakan",
    "haveli",
    "khed",
    "mulshi",
    "phaltan",
  ],
  chennai: [
    "madras",
    "chennai, tamil nadu",
    "madras, tamil nadu",
    "chennai, tamil nadu, india",
    "madras, tamil nadu, india",
    "chennai, india",
    "madras, india",
    "greater chennai area",
    "chennai metropolitan area",
    "chennai area",
  ],
  kolkata: [
    "calcutta",
    "kolkata, west bengal",
    "calcutta, west bengal",
    "kolkata, west bengal, india",
    "calcutta, west bengal, india",
    "kolkata, india",
    "calcutta, india",
    "greater kolkata area",
    "kolkata metropolitan area",
    "kolkata area",
    "haldia",
  ],
  ahmedabad: [
    "ahmedabad, gujarat",
    "ahmedabad, gujarat, india",
    "ahmedabad, india",
    "amdavad",
    "greater ahmedabad area",
    "ahmedabad area",
    "gandhinagar",
    "gandhinagar, gujarat",
    "ahmedabad-gandhinagar",
  ],
  chandigarh: [
    "chandigarh, chandigarh",
    "chandigarh, india",
    "chandigarh area",
    "greater chandigarh area",
    "chandigarh tricity",
    "mohali",
    "panchkula",
    "mohali district",
    "sahibzada ajit singh nagar",
  ],
  jaipur: [
    "jaipur, rajasthan",
    "jaipur, rajasthan, india",
    "jaipur, india",
    "jaipur area",
    "greater jaipur area",
  ],
  kochi: [
    "cochin",
    "kochi, kerala",
    "cochin, kerala",
    "kochi, kerala, india",
    "cochin, kerala, india",
    "kochi, india",
    "cochin, india",
    "ernakulam",
    "ernakulam, kerala",
    "greater kochi area",
    "kochi area",
  ],
  indore: [
    "indore, madhya pradesh",
    "indore, madhya pradesh, india",
    "indore, m.p.",
    "indore, mp",
    "indore, india",
    "indore area",
    "greater indore area",
  ],
  coimbatore: [
    "coimbatore, tamil nadu",
    "coimbatore, tamil nadu, india",
    "coimbatore, india",
    "kovai",
    "coimbatore area",
    "greater coimbatore area",
  ],
  thiruvananthapuram: [
    "trivandrum",
    "thiruvananthapuram, kerala",
    "trivandrum, kerala",
    "thiruvananthapuram, kerala, india",
    "trivandrum, kerala, india",
    "thiruvananthapuram, india",
    "trivandrum, india",
    "tvm",
    "technopark",
  ],
  visakhapatnam: [
    "vizag",
    "visakhapatnam, andhra pradesh",
    "vizag, andhra pradesh",
    "visakhapatnam, andhra pradesh, india",
    "vizag, andhra pradesh, india",
    "visakhapatnam, india",
    "vizag, india",
    "visakhapatnam area",
    "vizag area",
  ],
  bhubaneswar: [
    "bhubaneswar, odisha",
    "bhubaneswar, orissa",
    "bhubaneswar, odisha, india",
    "bhubaneswar, india",
    "bhubaneswar area",
    "cuttack-bhubaneswar",
  ],
  lucknow: [
    "lucknow, uttar pradesh",
    "lucknow, uttar pradesh, india",
    "lucknow, u.p.",
    "lucknow, up",
    "lucknow, india",
    "lucknow area",
  ],
  bhopal: [
    "bhopal, madhya pradesh",
    "bhopal, madhya pradesh, india",
    "bhopal, india",
  ],
  faridabad: [
    "faridabad, haryana",
    "faridabad, haryana, india",
    "faridabad, india",
  ],
  goa: ["goa, india", "panaji", "panaji, goa", "north goa", "south goa"],
  guwahati: ["guwahati, assam", "guwahati, assam, india", "guwahati, india"],
  jabalpur: [
    "jabalpur, madhya pradesh",
    "jabalpur, madhya pradesh, india",
    "jabalpur, india",
  ],
  jamshedpur: [
    "jamshedpur, jharkhand",
    "jamshedpur, jharkhand, india",
    "jamshedpur, india",
  ],
  kakinada: [
    "kakinada, andhra pradesh",
    "kakinada, andhra pradesh, india",
    "kakinada, india",
  ],
  mysore: [
    "mysore, karnataka",
    "mysore, karnataka, india",
    "mysore, india",
    "mysuru",
  ],
  nagpur: [
    "nagpur, maharashtra",
    "nagpur, maharashtra, india",
    "nagpur, india",
  ],
  nashik: [
    "nashik, maharashtra",
    "nashik, maharashtra, india",
    "nashik, india",
    "greater nashik area",
  ],
  prayagraj: [
    "prayagraj, uttar pradesh",
    "prayagraj, uttar pradesh, india",
    "allahabad",
  ],
  puducherry: [
    "puducherry, puducherry",
    "puducherry, puducherry, india",
    "pondicherry",
  ],
  rajkot: ["rajkot, gujarat", "rajkot, gujarat, india", "greater rajkot area"],
  surat: ["surat, gujarat", "surat, gujarat, india", "surat, india"],
  vadodara: [
    "vadodara, gujarat",
    "vadodara, gujarat, india",
    "baroda",
    "greater vadodara area",
  ],
  vijayawada: [
    "vijayawada, andhra pradesh",
    "vijayawada, andhra pradesh, india",
    "vijayawada east",
  ],
};

// --- Tech Stack Configuration ---
export const TECH_KEYWORDS = {
  // --- SoftwareDEV (Languages & Core) ---
  JavaScript: [/\bjavascript\b/i, /\bjs\b/i, /\bes6\+\b/i, /\becmascript\b/i],
  TypeScript: [/\btypescript\b/i, /\bts\b/i],
  Python: [/\bpython\b/i, /\bcpython\b/i, /\bpy\b/i, /\bpypi\b/i, /\bpep8\b/i],
  Java: [/\bjava\b/i, /\bjdk\b/i, /\bjvm\b/i, /\bjee\b/i],
  "C#": [/\bc#\b/i, /\.net\b/i, /\bdotnet\b/i, /\basp\.net\b/i],
  "C++": [/\bc\+\+\b/i, /\bcpp\b/i, /\bstl\b/i],
  Go: [/\bgolang\b/i, /\bgo\b/i], // \b is crucial here
  Rust: [/\brust\b/i, /\brustlang\b/i],
  Swift: [/\bswift\b/i, /\bswiftui\b/i],
  Kotlin: [/\bkotlin\b/i, /\bjetpack ?compose\b/i],

  // --- SoftwareDEV (Frontend & Mobile) ---
  React: [/\breact\b/i, /\breact\.js\b/i, /\breactjs\b/i, /\breact native\b/i],
  Angular: [/\bangular\b/i, /\bangularjs\b/i, /\bngx\b/i],
  Vue: [/\bvue\b/i, /\bvue\.js\b/i, /\bvuejs\b/i, /\bnuxt\b/i],
  Flutter: [/\bflutter\b/i, /\bdart\b/i],
  Tailwind: [/\btailwind\b/i, /\btailwindcss\b/i],

  // --- SoftwareDEV (Backend) ---
  NodeJS: [/\bnode\.js\b/i, /\bnodejs\b/i, /\bnode\b/i, /\bnpm\b/i],
  Spring: [/\bspring ?boot\b/i, /\bspring ?framework\b/i, /\bspring mvc\b/i],
  Django: [/\bdjango\b/i, /\bdrf\b/i, /django rest framework/i],
  FastAPI: [/\bfastapi\b/i, /fast api/i],
  GraphQL: [/\bgraphql\b/i, /\bapollo\b/i],

  Git: [/\bgit\b/i, /\bgit ?hub\b/i, /\bgit ?lab\b/i, /\bbit ?bucket\b/i],

  // --- DataEngg (Data Engineering) ---
  BigData: [
    /\bhadoop\b/i,
    /\bspark\b/i,
    /\bpyspark\b/i,
    /\bhive\b/i,
    /\bmapreduce\b/i,
  ],
  DataStreaming: [
    /\bkafka\b/i,
    /\brabbitmq\b/i,
    /\bactivemq\b/i,
    /\bpulsar\b/i,
  ],
  DataOrchestration: [
    /\bairflow\b/i,
    /\bdagster\b/i,
    /\bprefect\b/i,
    /\bluigi\b/i,
  ],
  DataWarehouse: [
    /\bsnowflake\b/i,
    /\bredshift\b/i,
    /\bbigquery\b/i,
    /\bdatabricks\b/i,
    /\bteradata\b/i,
  ],
  ETL: [
    /\betl\b/i,
    /\btalend\b/i,
    /\binformatica\b/i,
    /\bmatillion\b/i,
    /\bglue\b/i,
  ],

  // --- ML/AI ---
  DataScience: [
    /\bpandas\b/i,
    /\bnumpy\b/i,
    /\bmatplotlib\b/i,
    /\bseaborn\b/i,
    /\bjupyter\b/i,
  ],
  MachineLearning: [
    /\bmachine learning\b/i,
    /\bml\b/i,
    /\bscikit-learn\b/i,
    /\bsklearn\b/i,
  ],
  DeepLearning: [
    /\btensorflow\b/i,
    /\bpytorch\b/i,
    /\bkeras\b/i,
    /\bopencv\b/i,
    /\bcomputer ?vision\b/i,
  ],
  GenAI: [
    /\bgenai\b/i,
    /\bgenerative ai\b/i,
    /\bllm\b/i,
    /\bgpt\b/i,
    /\bchatgpt\b/i,
    /\bhugging ?face\b/i,
    /\blangchain\b/i,
    /\bllama\b/i,
    /\bollama\b/i,
  ],

  // --- DevOps/SRE ---
  AWS_Cloud: [
    /\baws\b/i,
    /\bec2\b/i,
    /\blambda\b/i,
    /\bs3\b/i,
    /\bcloudformation\b/i,
    /\bamazon web services\b/i,
  ],
  Azure_Cloud: [
    /\bazure\b/i,
    /\bazure ?devops\b/i,
    /\baks\b/i,
    /\bblob storage\b/i,
  ],
  Google_Cloud: [/\bgcp\b/i, /\bgoogle ?cloud\b/i, /\bgke\b/i, /\bbigtable\b/i],
  Containerization: [
    /\bdocker\b/i,
    /\bdockercompose\b/i,
    /\bk8s\b/i,
    /\bkubernetes\b/i,
    /\bhelm\b/i,
    /\bopenshift\b/i,
  ],
  IaC: [
    /\bterraform\b/i,
    /\bansible\b/i,
    /\bpulumi\b/i,
    /\bchef\b/i,
    /\bpuppet\b/i,
    /\bcloudformation\b/i,
  ],
  CI_CD: [
    /\bjenkins\b/i,
    /\bgitlab ci\b/i,
    /\bgithub actions\b/i,
    /\bazure devops\b/i,
    /\bcircleci\b/i,
    /\bargo\b/i,
  ],
  Observability: [
    /\bprometheus\b/i,
    /\bgrafana\b/i,
    /\bdatadog\b/i,
    /\bsplunk\b/i,
    /\belk ?stack\b/i,
    /\bnew ?relic\b/i,
    /\bopentelemetry\b/i,
  ],
  SRE: [
    /\bsre\b/i,
    /\bsite ?reliability\b/i,
    /\bslo\b/i,
    /\bsli\b/i,
    /\berror budget\b/i,
  ],

  // --- SoftwareQA ---
  Automation_Tools: [
    /\bselenium\b/i,
    /\bseleniumbase\b/i,
    /\bplaywright\b/i,
    /\bprotractor\b/i,
    /\bcypress\b/i,
    /\bpuppeteer\b/i,
    /\bweb ?driver\b/i,
    /\bwebdriverio\b/i,
    /\bnightwatch\b/i,
    /\bcucumber\b/i,
    /\bgherkin\b/i,
    /\bpytest\b/i,
    /\btest ?ng\b/i,
  ],
  ManualTest: [
    /\bmanual testing\b/i,
    /manual tester/i,
    /manual test/i,
    /\bmanualtesting\b/i,
    /\bmanual and automation\b/i,
    /\bmanual\s?\+\s?automation\b/i,
    /\bmanual and automated\b/i,
  ],
  MobileTest: [/\bappium\b/i, /\bxcuitest\b/i, /\bespresso\b/i],
  APITest: [
    /\brest ?assured\b/i,
    /\bpost ?man\b/i,
    /\bnewman\b/i,
    /\bsoap ?ui\b/i,
    /\bkarate\b/i,
  ],
  PerfTest: [/\bjmeter\b/i, /\bload ?runner\b/i, /\bgatling\b/i, /\bk6\b/i],

  // --- Security ---
  AppSec: [
    /\bowasp\b/i,
    /\bburp suite\b/i,
    /\bmetasploit\b/i,
    /\bzap\b/i,
    /\bsast\b/i,
    /\bdast\b/i,
  ],
  NetworkSec: [
    /\bwireshark\b/i,
    /\bnmap\b/i,
    /\bfirewall\b/i,
    /\bids\b/i,
    /\bips\b/i,
    /\bsiem\b/i,
  ],
  IdentitySec: [
    /\bkeycloak\b/i,
    /\biam\b/i,
    /\boauth\b/i,
    /\bsaml\b/i,
    /\bokta\b/i,
    /\bactive directory\b/i,
  ],
  Compliance: [
    /\bcissp\b/i,
    /\bceh\b/i,
    /\biso 27001\b/i,
    /\bgdpr\b/i,
    /\bsoc2\b/i,
  ],

  // --- HardwareQA ---
  Instrumentation: [
    /\boscilloscope\b/i,
    /\bmultimeter\b/i,
    /\bspectrum analyzer\b/i,
    /\blogic analyzer\b/i,
  ],
  Embedded_Tools: [
    /\bfpga\b/i,
    /\bverilog\b/i,
    /\bvhdl\b/i,
    /\bmicrocontroller\b/i,
    /\bartos\b/i,
    /\bfirmware\b/i,
  ],
  HardwareTest: [
    /\bpcb\b/i,
    /\bsoldering\b/i,
    /\baltium\b/i,
    /\blabview\b/i,
    /\bmatlab\b/i,
  ],
  // --- Operating Systems ---
  Linux_Unix: [
    /\blinux\b/i,
    /\bunix\b/i,
    /\bred ?hat\b/i,
    /\brhel\b/i,
    /\bubuntu\b/i,
    /\bdebian\b/i,
    /\bcentos\b/i,
    /\bfedora\b/i,
    /\bsuse\b/i,
    /\balpine\b/i,
    /\barch linux\b/i,
    /\bsolaris\b/i,
    /\baix\b/i,
    /\bhp-ux\b/i,
  ],
  Windows: [
    /\bwindows\b/i,
    /\bwindows server\b/i,
    /\bwin ?server\b/i,
    /\bwsl\b/i,
  ],
  MacOS: [/\bmac ?os\b/i, /\bos ?x\b/i],

  // Critical for HardwareQA / Embedded / Robotics roles
  Embedded_RTOS: [
    /\brtos\b/i,
    /\bvxworks\b/i,
    /\bqnx\b/i,
    /\bfreertos\b/i,
    /\bzephyr\b/i,
    /\bthreadx\b/i,
    /\bmicrium\b/i,
    /\bembedded linux\b/i,
  ],

  // --- RPA (Robotic Process Automation) ---
  RPA_Tools: [
    /\buipath\b/i,
    /\bautomation anywhere\b/i,
    /\bblue prism\b/i,
    /\bpower automate\b/i,
    /\bopenrpa\b/i,
  ],

  // --- DBA (Database Admin) ---
  RDBMS: [
    /\bpostgresql\b/i,
    /\bpostgres\b/i,
    /\bmysql\b/i,
    /\boracle db\b/i,
    /\bduckdb\b/i,
    /\bmssql\b/i,
    /\bsql server\b/i,
    /\bpl\/sql\b/i,
    /\bt-sql\b/i,
    /\bsqlite\b/i,
  ],
  NoSQL_DB: [
    /\bmongodb\b/i,
    /\bmongo\b/i,
    /\bcassandra\b/i,
    /\bdynamodb\b/i,
    /\bredis\b/i,
    /\belasticsearch\b/i,
    /\blmdb\b/i,
    /\bleveldb\b/i,
    /\brocksdb\b/i,
    /\bberkeleydb\b/i,
  ],
  DB_Mgmt: [
    /\bstored procedures\b/i,
    /\bsharding\b/i,
    /\breplication\b/i,
    /\bdatabase tuning\b/i,
  ],

  // --- Management ---
  Agile_Scrum: [
    /\bagile\b/i,
    /\bscrum\b/i,
    /\bkanban\b/i,
    /\bsafe\b/i,
    /\bsprint planning\b/i,
    /\bpmp\b/i,
    /\bprince2\b/i,
    /\bcsm\b/i,
    /\bpsm\b/i,
  ],
  Agile_Tools: [
    /\bjira\b/i,
    /\bconfluence\b/i,
    /\bazure boards\b/i,
    /\blinear\b/i,
    /\bclickup\b/i,
  ],

  // --- Vendor Specific Certifications ---
  Cert_AWS: [
    /\baws certified\b/i,
    /\b(aws|amazon).+architect\b/i, // Catch "AWS Solution Architect"
    /\b(aws|amazon).+developer\b/i, // Catch "AWS Developer"
    /\b(aws|amazon).+sysops\b/i,
    /\b(aws|amazon).+devops\b/i,
    /\b(aws|amazon).+specialty\b/i,
    /\bsaa-c0[1-3]\b/i, // Specific Exam Codes
    /\bdop-c0[1-2]\b/i,
    /\bsap-c0[1-2]\b/i,
  ],
  Cert_Azure: [
    /\bazure certified\b/i,
    /\bmicrosoft certified.+azure\b/i,
    /\baz-\d{3,4}\b/i, // Catch AZ-900, AZ-104, etc.
    /\bdp-\d{3}\b/i, // Data (DP-203)
    /\bai-\d{3}\b/i, // AI (AI-102)
    /\bsc-\d{3}\b/i, // Security (SC-200)
    /\bmcsd\b/i, // Legacy Microsoft
    /\bmcsa\b/i,
  ],
  Cert_GCP: [
    /\bgoogle cloud certified\b/i,
    /\bgcp certified\b/i,
    /\bprofessional cloud architect\b/i,
    /\bassociate cloud engineer\b/i,
    /\bprofessional data engineer\b/i,
    /\bprofessional cloud security\b/i,
  ],

  // --- Specialized Data & AI Vendors ---
  Cert_Databricks: [
    /\bdatabricks certified\b/i,
    /\bdatabricks.+associate\b/i,
    /\bdatabricks.+professional\b/i,
    /\bspark certified\b/i, // Often linked to Databricks contexts
  ],
  Cert_Snowflake: [
    /\bsnowflake certified\b/i,
    /\bsnowpro\b/i, // Their official cert name
    /\bsnowpro core\b/i,
  ],
  Cert_Tableau: [
    /\btableau certified\b/i,
    /\btableau desktop\b/i,
    /\btableau server\b/i,
  ],

  // --- Networking & Infrastructure Vendors ---
  Cert_Cisco: [
    /\bcisco certified\b/i,
    /\bccna\b/i,
    /\bccnp\b/i,
    /\bccie\b/i,
    /\bdevnet\b/i,
  ],
  Cert_HashiCorp: [
    /\bhashicorp certified\b/i,
    /\bterraform associate\b/i,
    /\bvault (associate|operations)\b/i,
    /\bconsul (associate|operations)\b/i,
  ],
  Cert_RedHat: [
    /\bred ?hat certified\b/i,
    /\brhce\b/i,
    /\brhcsa\b/i,
    /\bopenshift.+administrator\b/i,
  ],
  Cert_LinuxFoundation: [
    // CNCF is under Linux Foundation
    /\blinux foundation certified\b/i,
    /\bcka\b/i, // Kubernetes Admin
    /\bckad\b/i, // Kubernetes App Dev
    /\bcks\b/i, // Kubernetes Security
    /\bkcna\b/i,
  ],

  // --- Quality Assurance & Methodology Vendors ---
  Cert_ISTQB: [
    /\bistqb\b/i,
    /\biseb\b/i, // Older/Regional variant often paired
    /\badvanced level (test|tester)\b/i, // Contextual, use carefully
    /\bcertified tester\b/i,
  ],
  Cert_ScrumOrg: [
    // Vendor: Scrum.org (The "Professional" series)
    /\bpsm\s?[i|1|2|ii]?\b/i, // Professional Scrum Master
    /\bpspo\b/i, // Professional Scrum Product Owner
    /\bprofessional scrum\b/i,
  ],
  Cert_ScrumAlliance: [
    // Vendor: Scrum Alliance (The "Certified" series)
    /\bcsm\b/i, // Certified Scrum Master
    /\bcspo\b/i, // Certified Scrum Product Owner
    /\bcsp\b/i, // Certified Scrum Professional
  ],
  Cert_PMI: [
    // Vendor: Project Management Institute
    /\bpmp\b/i,
    /\bcapm\b/i,
    /\bpmi-acp\b/i,
    /\bpgmp\b/i,
  ],

  // --- Security Vendors ---
  Cert_CompTIA: [
    /\bcomptia\b/i,
    /\bsec\+\b/i, // Short for Security+
    /\bsecurity\+\b/i,
    /\bnet\+\b/i, // Network+
    /\bnetwork\+\b/i,
    /\bcysa\+\b/i,
    /\bcasp\+\b/i,
  ],
  Cert_ISC2: [
    /\bisc2\b/i,
    /\bcissp\b/i,
    /\bccsp\b/i, // Cloud Security
    /\bsscp\b/i,
  ],
  Cert_OffSec: [
    // Offensive Security (Kali creators)
    /\boffensive security\b/i,
    /\boscp\b/i,
    /\bosce\b/i,
    /\boswp\b/i,
  ],
  Cert_ISACA: [/\bisaca\b/i, /\bcism\b/i, /\bcisa\b/i, /\bcrisc\b/i],

  // --- Enterprise Software Vendors ---
  Cert_Salesforce: [
    /\bsalesforce certified\b/i,
    /\bsalesforce administrator\b/i,
    /\bsalesforce developer\b/i,
    /\bplatform app builder\b/i,
  ],
  Cert_Oracle: [
    /\boracle certified\b/i,
    /\bocjp\b/i, // Java Programmer
    /\bocp\b/i,
    /\boca\b/i,
    /\bocm\b/i,
  ],
};

const BASE_REMOVE_TITLES = [
  "| India",
  "|| Pan India",
  "_PAN India",
  "-PAN India",
  "- PAN India",
  "PAN India",
  ", India",
  ",India",
  "- India)",
  "- India",
  "(IND) ",
  "(IND)",
  " (INDIA)",
  "(India)",
  "(India based role – Hyderabad)",
  "- NCR Region",
  "| AiFA Labs",
  "| Fulltime",
  "-- For Multiple locations",
  "- For Multiple locations",
  "-For Multiple locations",
  "For Multiple locations",
  "Multiple locations",
  "Locations",
  "Location",
  " NCR Region",
  "(Vizag)",
  "Interesting Job Opportunity",
  "In-Person Hiring Drive- ",
  "In-Person Hiring Drive",
  "Hiring Drive",
  "We are hiring",
  "We're Hiring",
  "We Are Hiring – ",
  "We are Hiring",
  "is Hiring! ",
  "is Hiring-",
  "is Hiring -",
  "is Hiring",
  "Speed Hiring_",
  "Speed Hiring ",
  "Hiring Immediately",
  " | Immediate Joiner |",
  "| Immediate Joiner",
  "(Immediate Joiner)",
  "/ Immediate Joiners",
  "| Immediate Joiners",
  "- Immediate Joiners",
  "- Immediate Joiners Preferred",
  "| Immediate Joiners Preferred",
  "| Immediate Joiners",
  "/ Immediate Joiners",
  "(Immediate Joiners Only)",
  "(Immediate Joiners)",
  "Need Immediate Joiner",
  "Urgent Opening- ",
  "Urgent Job Opening for ",
  "Urgent Opening for",
  "Urgent Opening ",
  "Urgent ",
  "!!!",
  ", IMMEDIATE JOINER. Across",
  "Immediate opening for ",
  "Hiring Immediately",
  "- ASAP Joiner Required",
  "ASAP Joiner Required",
  "#1 Apply fast!",
  "Apply fast!",
  "TCS Is Hiring For ",
  "Hiring for ",
  "[Upcoming Roles] ",
  "Upcoming Roles",
  "Great Opportunity in TCS!",
  "Great Opportunity",
  "DeltaBits is Hiring — ",
  "🚀 is Hiring in Pune! ",
  "🚀 is Hiring in",
  "is Hiring in",
  "is Hiring",
  "| Pan",
  "Title ",
  " - Mumbai",
  ");/Chennai; Permanent",
  "; Permanent",
  " Permanent",
  ";/Chennai",
  "_Chennai",
  "- Chennai",
  " - Pune",
  "|Bangalore",
  "_Bangalore",
  "- Bangalore",
  "- Mumbai",
  "- Hyderabad",
  " at Pune location.",
  " ()",
  "- E",
  "- EY",
  "India",
];

const prefix = [
  ", ", // e.g., ", Bangalore"
  ",", // e.g., ",Bangalore"
  "– ", // e.g., "– Bangalore" (en-dash)
  "- ", // e.g., "- Bangalore" (hyphen)
  "-", // e.g., "-Bangalore"
  "| ", // e.g., "| Bangalore"
  " ", // e.g., " Bangalore"
];

/**
 * Generates a Set of remove strings from the CITY_ALIAS object.
 */
function generateCityNameCombos(aliases) {
  const nameCombos = new Set();

  // Get a single, flat array of all aliases (e.g., "bangalore", "whitefield", "ncr")
  const allAliases = Object.values(aliases).flat();

  allAliases.forEach((alias) => {
    if (!alias) {
      return;
    }
    // 1. Create a Title-Cased version (e.g., "bangalore" -> "Bangalore")
    const titleCasedAlias = alias.charAt(0).toUpperCase() + alias.slice(1);
    // 2. Create an Upper-Cased version (e.g., "ncr" -> "NCR")
    const upperCasedAlias = alias.toUpperCase();

    // Apply all prefixes to both versions
    prefix.forEach((prefix) => {
      // Add the title-cased version (e.g., ", Bangalore", ", Whitefield")
      nameCombos.add(prefix + titleCasedAlias);
      // Only add the all-caps version if it's different and short (4 chars or less)
      // This adds ", NCR" but avoids adding ", BANGALORE URBAN"
      if (titleCasedAlias !== upperCasedAlias && alias.length <= 4) {
        nameCombos.add(prefix + upperCasedAlias);
      }
    });
  });
  return nameCombos;
}

const cityNameCombos = generateCityNameCombos(CITY_ALIAS);
export const REMOVE_TITLES = [
  ...new Set([...BASE_REMOVE_TITLES, ...cityNameCombos]),
];
