// Job Role titles for searching
export const JOB_KEYWORDS = [
  "API Test Automation",
  "Cypress Automation Engineer",
  "Director of QA",
  "Head of Quality Engineering",
  "Lead Automation Engineer",
  "Lead QA Engineer",
  "Mobile Automation Engineer",
  "Performance QA Engineer",
  "Performance Test Engineer",
  "Playwright Automation",
  "Principal Automation Engineer",
  "Principal Quality Engineer",
  "Principal SDET",
  "Python Automation",
  "QA Automation Architect",
  "QA Automation Lead",
  "QA Manager (Automation)",
  "Quality Engineering Lead",
  "SDET Lead",
  "Selenium Automation",
  "Senior Automation Engineer",
  "Senior QA Automation Engineer",
  "Senior SDET (Software Development Engineer in Test)",
  "Senior Test Automation Engineer",
  "Senior Test Automation Specialist",
  "Senior Test Engineer",
  "Staff SDET Automation Engineer",
  "Staff Software Development Engineer in Test",
  "Test Automation Lead",
];

// LinkedIn Job Search Query to get recent posts
export const LINKEDIN_SEARCH_QUERY = {
  location: "India",
  jobType: "full time",
  sortBy: "recent", // relevant or recent
  dateSincePosted: "24hr",
  experienceLevel: "senior",
  //valid values: internship, entry level, associate, senior, director, executive
  limit: "20",
  page: "0",
};

// Classification Categories, keywords and negative associations.
export const CATEGORIES = {
  SoftwareDEV: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "software engineer",
      "full stack",
      "application developer",
      "web developer",
      "solution architect",
      "software architect",
      "api development",
      "design patterns",
      "microservices",
      "rest api",
      "solution engineer",
      "feature engineering",
      "model training",
      "data pipeline",
      "computer vision",
    ],
    terms: [
      "developer",
      "programmer",
      "frontend",
      "backend",
      "mobile",
      "javascript",
      "typescript",
      "java",
      "c#",
      ".net",
      "python",
      "golang",
      "go",
      "ruby",
      "php",
      "swift",
      "kotlin",
      "scala",
      "rust",
      "c++",
      "objective-c",
      "node.js",
      "nodejs",
      "react",
      "angular",
      "vue",
      "svelte",
      "jquery",
      "spring",
      "spring boot",
      "django",
      "flask",
      "fastapi",
      "rails",
      "laravel",
      "express.js",
      "graphql",
      "apollo",
      "architecture",
      "oop",
      "functional programming",
      "sql",
      "nosql",
      "mongodb",
      "postgres",
      "mysql",
      "database",
      "algorithm",
      "data structures",
      "coding",
      "genai",
      "rag",
      "sagemaker",
      "bedrock",
    ],
    negative: [
      // QA / Testing
      "qa",
      "quality",
      "tester",
      "sdet",
      "automation tester",
      "test plan",
      "test case",
      "manual testing",
      "bug tracking",
      "regression testing",
      // DevOps/SRE
      "devops",
      "sre",
      "site reliability",
      "platform engineer",
      "infrastructure",
      "ci/cd",
      "jenkins",
      "prometheus",
      "grafana",
      "on-call",
      "incident",
      // Hardware/Mech
      "hardware",
      "pcb",
      "rtl",
      "fpga",
      "asic",
      "embedded",
      "firmware",
      "oscilloscope",
      "mechanical",
      "mechatronics",
      "electromechanical",
      "3d cad",
      "piping",
      // Non-dev recruiting/ops
      "talent acquisition",
      "recruitment",
      "hiring",
      "sourcing candidates",
      "offer letter",
      "compensation",
      "procurement",
      "vendor management",
      "supplier",
      "iso 9001",
      "supply chain",
      // Construction & civil
      "civil",
      "construction",
      "mep",
      // Out-of-scope tech mgmt
      "product manager",
      "project manager",
      "agile coach",
      "scrum master",
      "business intelligence",
    ],
  },

  SoftwareQA: {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "quality engineer",
      "quality assurance",
      "test engineer",
      "software developer in test",
      "test case",
      "test plan",
      "test strategy",
      "test execution",
      "bug report",
      "api testing",
      "ui testing",
      "regression testing",
      "functional testing",
      "performance testing",
      "load testing",
      "acceptance testing",
      "integration testing",
      "e2e testing",
      "black box",
      "white box",
      "software quality engineer",
      "manual and automation testing",
      "test coverage",
      "defect tracking",
      "defect triage",
      "testing web applications",
      "qa automation",
      "qa specialist",
      "qa architect",
      "selenium testing",
      "rest assured",
      "ready api",
      "smoke test",
      "test management tools",
      "root cause analysis",
      "agile qa",
      "compliance testing",
    ],
    terms: [
      "qa",
      "quality",
      "tester",
      "testing",
      "sdet",
      "automation",
      "selenium",
      "seleniumbase",
      "cypress",
      "playwright",
      "postman",
      "soapui",
      "jmeter",
      "testrail",
      "qtest",
      "jira",
      "appium",
      "webdriverio",
      "k6",
      "gatling",
      "sonarqube",
      "uipath test",
      "tosca",
      "tdd",
      "bdd",
      "defect",
      "manual testing",
      "validation",
      "logs",
      "testng",
      "junit",
      "zephyr",
      "post-release",
      "post-implementation",
      "bug bash",
      "sanity testing",
      "smoke testing",
    ],
    negative: [
      // Hardware
      "hardware",
      "pcb",
      "rtl",
      "firmware",
      "fpga",
      "asic",
      "oscilloscope",
      "electrical",
      // DevOps/SRE
      "sre",
      "site reliability",
      "platform engineer",
      "on-call",
      "incident management",
      // Pure architecture build roles
      "software architect",
      "building features",
      // Construction/Civil/Manufacturing
      "mep",
      "civil",
      "civil engineering",
      "construction",
      "plumbing",
      "fire fighting",
      "real estate",
      "residential construction",
      "structural",
      // Industry QA that is not SoftwareQA (we avoid misclassifying):
      "qms",
      "snagging",
      "sop",
      "itp",
      // Heavier BI/warehouse (goes to DataEngg)
      "data warehousing",
      "etl",
      // Non-tech roles
      "talent acquisition",
      "recruitment",
      "hiring",
      "mechanical",
      "casting",
      "machining",
      "manufacturing",
      "emotor",
      "electric vehicle",
      "procurement",
      "vendor management",
      "contracts",
      "supplier",
      "iso 9001",
      "cost-saving",
      "logistics",
      "supply chain",
      // Product/Program
      "product roadmap",
      "stakeholder management",
      "budget",
      // Pharma
      "gmp",
      "cgmp",
      "fda",
      "apqr",
      "qms",
      "validation protocol",
      "21 cfr",
      "sop",
      "biosimilars",
      "hplc",
      "gc",
      "karl fischer",
      "chromatogram",
      "dissolution",
      // other
      "garment",
      "textile",
      "fabric",
      "merchandiser",
      "vendor location",
      "inline inspection",
      "final inspection",
      "production quality",
      "sample evaluation",
      "risk analysis",
      "buyer requirements",
      "raw materials",
      "export house",
      "retail quality",
      "pattern measuring",
      "accessories inspection",
      "measurement review",
      "non-conformity",
      "factory quality",
      "production approvals",
      "quality communication",
    ],
  },

  HardwareQA: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "hardware test",
      "validation engineer",
      "system validation",
      "silicon validation",
      "post-silicon",
      "pre-silicon",
      "board bring-up",
      "manufacturing test",
      "power integrity",
      "mechanical engineer",
      "mechanical design engineer",
      "electric motor",
      "electric vehicle",
      "manufacturing drawings",
      "bill of materials",
      "component development",
      "industrial manufacturing",
      "geometric dimensioning",
      "gd&t",
      "manufacturing processes",
      "additive manufacturing",
      "aluminum die casting",
      "plastic injection moulding",
    ],
    terms: [
      "hardware",
      "pcb",
      "rtl",
      "fpga",
      "asic",
      "embedded",
      "firmware",
      "board design",
      "schematic",
      "layout",
      "lab",
      "oscilloscope",
      "signal integrity",
      "logic analyzer",
      "spectrum analyzer",
      "jtag",
      "debugger",
      "multimeter",
      "test fixture",
      "electrical",
      "bench testing",
      "emc",
      "emi",
      "mechatronics",
      "electromechanical",
      "3d cad",
      "sensors",
      "valves",
      "fmea",
      "prototypes",
      "emotor",
      "automotive",
      "drivetrain",
      "casting",
      "machining",
      "stamping",
      "catia",
      "ansys",
    ],
    negative: [
      // Software/web
      "web",
      "frontend",
      "backend",
      "microservices",
      "ui",
      "api testing",
      "react",
      "node.js",
      "javascript",
      "css",
      "html",
      "java",
      "c#",
      "full stack",
      // Cloud/devops
      "cloud",
      "aws",
      "gcp",
      "azure",
      "devops",
      "sre",
      "ci/cd",
      // Non-relevant
      "mep",
      "civil",
      "construction",
      "plumbing",
      "talent acquisition",
      "recruitment",
      "hiring",
      "product roadmap",
      "stakeholder management",
      "etl",
      "data lake",
      // Pharma
      "apqr",
      "biosimilars",
      "oos",
      "21 cfr",
      "batch record",
      "vmp",
    ],
  },

  PharmaQA: {
    weight: 1,
    titleBoost: 1.5,
    phrases: [
      "quality management system",
      "gmp compliance",
      "process validation",
      "computer system validation",
      "apqr",
      "quality oversight",
      "regulatory audits",
      "batch record review",
      "corrective and preventive action",
      "change control management",
      "quality control for pharma",
      "inspection readiness",
      "validation protocol and report",
      "quality operations and gmp",
      "biosimilar operations",
      "system compliance",
      "design control quality management",
      "analytical method validation",
      "impurity profiling",
      "release testing",
    ],
    terms: [
      "qms",
      "gmp",
      "cgmp",
      "fda",
      "ema",
      "oos",
      "oot",
      "capa",
      "apqr",
      "validation",
      "protocol",
      "report",
      "tpms", // Third-Party Manufacturers
      "biosimilars",
      "pharmaceutical",
      "biotech",
      "medical device",
      "audit",
      "inspection",
      "deviation",
      "change control",
      "batch processing",
      "sop",
      "bpr", // Batch Production Record / Batch Processing Record
      "bmr", // Batch Manufacturing Record
      "dcs", // Document Control System
      "ensur", // Specific system name (ENSUR 4.2)
      "iso13485",
      "eumdd",
      "iec 62304",
      "21 cfr part",
      "vmp", // Validation Master Plan
      "csv", // Computer System Validation
      "iq", // Installation Qualification
      "oq", // Operational Qualification
      "pq", // Performance Qualification
      "risk assessment",
      "quality review",
      "hplc",
      "pharma",
      "hipaa",
      "argus safety",
      "health science",
      "gc",
      "uv",
      "ir",
      "karl fischer",
      "lmis",
      "cds",
      "chromatogram",
    ],
    negative: [
      // Exclude generic SoftwareQA terms unless paired with Pharma terms
      "selenium",
      "cypress",
      "python",
      "javascript",
      "java",
      "ui testing",
      "api testing",
      "sdet",
      // Exclude pure HardwareQA/Engineering terms
      "pcb",
      "rtl",
      "fpga",
      "mechanical",
      "electromechanical",
      "3d cad",
      // Exclude generic IT roles (unless compliance/validation)
      "full stack",
      "backend",
      "frontend",
      "microservices",
      "devops",
      "sre",
      "kubernetes",
    ],
  },

  "DevOps/SRE": {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "site reliability",
      "platform engineer",
      "infrastructure engineer",
      "service mesh",
      "infrastructure as code",
      "platform as code",
      "incident management",
      "high availability",
      "disaster recovery",
    ],
    terms: [
      "devops",
      "sre",
      "reliability engineer",
      "cloud engineer",
      "kubernetes",
      "k8s",
      "docker",
      "helm",
      "terraform",
      "ansible",
      "puppet",
      "chef",
      "saltstack",
      "container",
      "ci/cd",
      "github actions",
      "jenkins",
      "gitlab ci",
      "circleci",
      "travis ci",
      "prometheus",
      "grafana",
      "observability",
      "pagerduty",
      "datadog",
      "cloudwatch",
      "splunk",
      "elk",
      "elasticsearch",
      "logstash",
      "kibana",
      "new relic",
      "cloud",
      "aws",
      "gcp",
      "azure",
      "istio",
      "envoy",
      "on-call",
      "incident",
      "postmortem",
      "iac",
      "automation",
      "scripting",
      "bash",
      "powershell",
      "slo",
      "sli",
      "sla",
      "scalability",
      "monitoring",
      "logging",
      "alerting",
    ],
    negative: [
      "manual testing",
      "test case",
      "ui automation",
      "qa",
      "quality assurance",
      "sdet",
      "test plan",
      "bug report",
      "selenium",
      "cypress",
      "frontend",
      "react",
      "angular",
      "vue",
      "ui/ux",
      "application developer",
      "hardware",
      "pcb",
      "fpga",
      "embedded",
      "firmware",
      "oscilloscope",
      "rtl",
      "talent acquisition",
      "recruitment",
      "hiring",
      "sourcing candidates",
      "offer letter",
      "compensation",
      "civil",
      "construction",
      "mep",
      "automotive",
      "mechanical",
      "product strategy",
      "business analyst",
      "scrum master",
      "tableau",
      "procurement",
      "vendor management",
      "supplier",
      "supply chain",
    ],
  },

  DataEngg: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "data engineer",
      "etl developer",
      "data pipeline",
      "data warehousing",
      "business intelligence",
      "big data",
      "data modeling",
      "data governance",
      "data quality assurance",
      "master data management",
      "analytics engineer",
    ],
    terms: [
      "spark",
      "hadoop",
      "hive",
      "kafka",
      "airflow",
      "etl",
      "elt",
      "data lake",
      "databricks",
      "dbt",
      "tableau",
      "power bi",
      "qlik",
      "snowflake",
      "redshift",
      "dynamodb",
      "bigquery",
      "nosql",
      "ssis",
      "ssas",
      "ssrs",
      "data vault",
      "fivetran",
      "stitch",
      "glue",
      "lakehouse",
    ],
    negative: [
      "frontend",
      "ui",
      "ux",
      "react",
      "angular",
      "vue",
      "mobile",
      "qa",
      "tester",
      "sdet",
      "manual testing",
      "firmware",
      "hardware",
      "pcb",
      "fpga",
      "oscilloscope",
      "mechanical",
      "incident management",
      "on-call",
      "kubernetes",
      "scrum master",
      "product roadmap",
      "stakeholder",
    ],
  },

  "ML/AI": {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "data scientist",
      "machine learning scientist",
      "applied scientist",
      "ml engineer",
      "ml research",
      "research scientist",
      "computer vision",
      "natural language processing",
      "nlp",
      "recommendation systems",
      "time series forecasting",
      "experiment design",
      "ab testing",
    ],
    terms: [
      "ml",
      "ai",
      "llm",
      "genai",
      "rag",
      "prompt engineering",
      "feature engineering",
      "model training",
      "model evaluation",
      "model tuning",
      "hyperparameter",
      "pytorch",
      "tensorflow",
      "sklearn",
      "xgboost",
      "lightgbm",
      "huggingface",
      "vector db",
      "faiss",
      "milvus",
      "weaviate",
      "sagemaker",
      "bedrock",
      "comet",
      "wandb",
      "mlflow",
      "notebook",
      "statistics",
      "bayesian",
      "regression",
      "classification",
      "clustering",
      "experiment tracking",
      "offline evaluation",
      "online metrics",
    ],
    negative: [
      "test case",
      "manual testing",
      "qa",
      "tester",
      "on-call",
      "incident",
      // DevOps
      "jenkins",
      "terraform",
      "kubernetes",
      "pcb",
      "rtl",
      "fpga",
      // Hardware
      "oscilloscope",
      "talent acquisition",
      "recruitment",
      "hiring",
      "product roadmap",
      "stakeholder management",
    ],
  },

  Security: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "security engineer",
      "application security",
      "cloud security",
      "product security",
      "security analyst",
      "security operations",
      "soc analyst",
      "penetration testing",
      "red team",
      "blue team",
      "threat detection",
      "security architecture",
      "identity and access management",
      "iam",
      "governance risk compliance",
      "grc",
      "risk management",
      "vulnerability management",
      "terminal security",
      "security operations",
      "access control and key management",
      "mock drills",
      "vvip movement",
    ],
    terms: [
      "infosec",
      "appsec",
      "secops",
      "siem",
      "soar",
      "splunk",
      "qrader",
      "sentinel",
      "crowdstrike",
      "okta",
      "auth0",
      "sso",
      "mfa",
      "oidc",
      "oauth",
      "nist",
      "iso 27001",
      "soc2",
      "pci-dss",
      "hipaa",
      "gdpr",
      "burp",
      "zap",
      "nessus",
      "qualys",
      "osint",
      "mitre att&ck",
      "owasp",
      "secrets scanning",
      "sast",
      "dast",
      "sca",
      "key management",
      "access control",
      "biometric",
      "concessionaires",
    ],
    negative: [
      "qa",
      "tester",
      "manual testing",
      "frontend",
      "react",
      "angular",
      "vue",
      "pcb",
      "fpga",
      "oscilloscope",
      "etl",
      "data warehousing",
      "scrum master",
      "product manager",
    ],
  },

  RPA: {
    weight: 1,
    titleBoost: 1.3,
    phrases: [
      "rpa developer",
      "uipath developer",
      "automation anywhere developer",
      "blue prism developer",
      "robotic process automation",
      "attended automation",
      "unattended automation",
      "UiPath Orchestrator",
      "UiPath Studio",
      "UiPath Assistant",
      "UiPath ReFramework",
      "UiPath Document Understanding",
      "UiPath AI Center",
      "UiPath Action Center",
      "UiPath Insights",
      "UiPath Governance",
      "UiPath Deployment",
      "UiPath Licensing",
      "UiPath Queue Management",
      "UiPath Trigger Management",
      "UiPath Asset Management",
      "UiPath Package Deployment",
      "UiPath Marketplace",
    ],
    terms: [
      "uipath",
      "automation anywhere",
      "blue prism",
      "orchestrator",
      "reframework",
      "workflow analyzer",
      "invoke workflow",
      "custom activity",
      "robot provisioning",
      "package publishing",
      "transaction item",
      "queue trigger",
      "automation hub",
      "document understanding",
      "ocr engines",
      "ai fabric",
      "action center",
      "insights dashboard",
    ],
    negative: [
      "qa",
      "test case",
      "manual testing",
      "kubernetes",
      "terraform",
      "jenkins",
      "pcb",
      "rtl",
      "fpga",
      // Physical/Aviation Security / Airport Ops
      "immigration",
      "customs",
      "airport",
      "terminal",
      "igia",
      "skytrax",
      "security operations",
      "key management",
      "access control",
      "biometric access",
      "mock drills",
      "vvip",
      "touting",
      "concessionaires",
      "house keeping agencies",
      // Cyber/DevOps terms
      "kubernetes",
      "terraform",
      "prometheus",
      "grafana",
      // QA specific test frameworks
      "selenium",
      "cypress",
      "postman",
      "api testing",
      "test case",
      "sdet",
      "recruitment",
      "talent acquisition",
      "hiring",
    ],
  },

  DBA: {
    weight: 1,
    titleBoost: 1.4,
    phrases: [
      "database administrator",
      "database reliability engineer",
      "performance tuning",
      "backup and recovery",
      "disaster recovery",
      "replication",
      "high availability",
    ],
    terms: [
      "oracle dba",
      "sql server dba",
      "mysql dba",
      "postgres dba",
      "pl/sql",
      "t-sql",
      "indexing",
      "query tuning",
      "partitioning",
      "rds",
      "aurora",
      "exadata",
      "asm",
      "golden gate",
      "logical replication",
    ],
    negative: [
      "etl",
      "spark",
      "airflow",
      "kubernetes",
      "terraform",
      "selenium",
      "cypress",
      "pcb",
      "rtl",
    ],
  },

  Management: {
    weight: 1,
    titleBoost: 1.8,
    phrases: [
      "product manager",
      "project manager",
      "scrum master",
      "agile coach",
      "product owner",
      "business analyst",
      "product strategy",
      "product roadmap",
      "stakeholder management",
      "user stories",
      "requirements gathering",
      "go-to-market",
      "pmp certified",
      "program manager",
      "delivery manager",
    ],
    terms: [
      "agile",
      "scrum",
      "kanban",
      "pmp",
      "csm",
      "jira",
      "confluence",
      "trello",
      "wbs",
      "budgeting",
      "timeline",
      "risk management",
      "stakeholder",
      "feature",
      "release",
      "mvp",
      "okr",
      "kpi",
      "gantt",
      "project",
      "product",
      "management",
      "analyst",
      "ux research",
      "market research",
      "roadmap",
      "portfolio",
    ],
    negative: [
      "coding",
      "javascript",
      "python",
      "java",
      "c#",
      "sql",
      "api development",
      "full stack",
      "backend",
      "frontend",
      "developer",
      "engineer",
      "qa",
      "tester",
      "sdet",
      "manual testing",
      "automation",
      "kubernetes",
      "terraform",
      "devops",
      "sre",
      "hardware",
      "pcb",
      "rtl",
      "firmware",
      "procurement",
      "vendor management",
      "supplier",
      "supply chain",
    ],
  },
};

// --- General Color Palette (for Company/Location) ---
export const GENERAL_COLOR_PALETTE = [
  { bg: "rgba(54, 162, 235, 0.7)" }, // Blue
  { bg: "rgba(255, 99, 132, 0.7)" }, // Red
  { bg: "rgba(75, 192, 192, 0.7)" }, // Green
  { bg: "rgba(153, 102, 255, 0.7)" }, // Purple
  { bg: "rgba(255, 159, 64, 0.7)" }, // Orange
  { bg: "rgba(255, 206, 86, 0.7)" }, // Yellow
  { bg: "rgba(201, 203, 207, 0.7)" }, // Grey
  { bg: "rgba(255, 0, 255, 0.7)" }, // Magenta
  { bg: "rgba(0, 255, 0, 0.7)" }, // Lime Green
  { bg: "rgba(128, 0, 0, 0.7)" }, // Maroon
  { bg: "rgba(0, 128, 128, 0.7)" }, // Teal
  { bg: "rgba(0, 0, 128, 0.7)" }, // Navy Blue
  { bg: "rgba(128, 128, 0, 0.7)" }, // Olive
  { bg: "rgba(128, 0, 128, 0.7)" }, // Plum/Dark Magenta
  { bg: "rgba(255, 105, 180, 0.7)" }, // Hot Pink
  { bg: "rgba(255, 215, 0, 0.7)" }, // Gold
  { bg: "rgba(173, 216, 230, 0.7)" }, // Light Blue
  { bg: "rgba(240, 128, 128, 0.7)" }, // Light Coral
  { bg: "rgba(144, 238, 144, 0.7)" }, // Light Green
  { bg: "rgba(238, 130, 238, 0.7)" }, // Violet
  { bg: "rgba(112, 128, 144, 0.7)" }, // Slate Grey
  { bg: "rgba(189, 183, 107, 0.7)" }, // Dark Khaki
  { bg: "rgba(255, 182, 193, 0.7)" }, // Light Pink
  { bg: "rgba(255, 228, 181, 0.7)" }, // Moccasin
  { bg: "rgba(100, 149, 237, 0.7)" }, // Cornflower Blue
  { bg: "rgba(255, 99, 71, 0.7)" }, // Tomato
  { bg: "rgba(60, 179, 113, 0.7)" }, // Medium Sea Green
  { bg: "rgba(72, 61, 139, 0.7)" }, // Dark Slate Blue
];

// --- Semantic Role Type Colors (for byRoleType) ---
export const ROLE_TYPE_COLOR_PALETTE = {
  SoftwareDEV: { bg: "rgba(54, 162, 235, 0.7)" }, // Blue
  SoftwareQA: { bg: "rgba(75, 192, 192, 0.7)" }, // Green
  Management: { bg: "rgba(255, 99, 132, 0.7)" }, // Red
  "ML/AI": { bg: "rgba(153, 102, 255, 0.7)" }, // Purple
  "DevOps/SRE": { bg: "rgba(255, 159, 64, 0.7)" }, // Orange
  DataEngg: { bg: "rgba(255, 206, 86, 0.7)" }, // Yellow
  HardwareQA: { bg: "rgba(0, 128, 128, 0.7)" }, // Teal
  PharmaQA: { bg: "rgba(60, 179, 113, 0.7)" }, // Medium Sea Green
  Security: { bg: "rgba(128, 0, 0, 0.7)" }, // Maroon
  RPA: { bg: "rgba(100, 149, 237, 0.7)" }, // Cornflower Blue
  DBA: { bg: "rgba(100, 136, 172, 0.7)" }, // Slate Grey
  Default: { bg: "rgba(201, 203, 207, 0.7)" }, // Grey (kept as default)
};

// Role-defining title nudges only (specific > generic). Order matters.
export const TITLE_NUDGES = [
  // --- SoftwareQA ---
  {
    regex: /\b(sdet|software\s*developer\s*in\s*test)\b/i,
    cat: "SoftwareQA",
    boost: 5,
  },
  {
    regex:
      /\b(qa\s*engineer|quality\s*engineer|test\s*automation|automation\s*tester)\b/i,
    cat: "SoftwareQA",
    boost: 4,
  },
  {
    regex: /\b(test\s*architect|qa\s*architect)\b/i,
    cat: "SoftwareQA",
    boost: 3,
  },

  // --- DevOps / SRE / Platform (infra) ---
  {
    regex: /\b(sre|site\s*reliability\s*engineer)\b/i,
    cat: "DevOps/SRE",
    boost: 5,
  },
  {
    regex:
      /\b(devops|platform\s*engineer|production\s*engineer|infrastructure\s*engineer)\b/i,
    cat: "DevOps/SRE",
    boost: 4,
  },

  // --- HardwareQA / Embedded / Silicon / Mechanical ---
  {
    regex:
      /\b(asic|fpga|rtl|post-?silicon|pre-?silicon|silicon\s*validation)\b/i,
    cat: "HardwareQA",
    boost: 5,
  },
  {
    regex:
      /\b(hardware|embedded|firmware|validation\s*engineer|mechatronics|electro-?mechanical|mechanical)\b/i,
    cat: "HardwareQA",
    boost: 4,
  },

  // --- Data Engineering / Analytics Engineering ---
  {
    regex:
      /\b(data\s*engineer|analytics\s*engineer|data\s*platform\s*engineer)\b/i,
    cat: "DataEngg",
    boost: 4,
  },
  {
    regex: /\b(etl\s*developer|data\s*architect)\b/i,
    cat: "DataEngg",
    boost: 3,
  },

  // --- Data Science / ML ---
  {
    regex: /\b(data\s*scientist|applied\s*scientist|research\s*scientist)\b/i,
    cat: "ML/AI",
    boost: 4,
  },
  // Ambiguous but useful signal; let description/keyword scoring finalize
  {
    regex:
      /\b(ml\s*engineer|machine\s*learning\s*engineer|computer\s*vision|nlp)\b/i,
    cat: "ML/AI",
    boost: 3,
  },

  // --- Security / InfoSec ---
  {
    regex:
      /\b(application\s*security|appsec|security\s*engineer|product\s*security|cloud\s*security)\b/i,
    cat: "Security",
    boost: 4,
  },
  {
    regex:
      /\b(soc\s*analyst|penetration\s*tester|red\s*team|blue\s*team|grc|governance\s*risk\s*compliance|iam)\b/i,
    cat: "Security",
    boost: 4,
  },

  // --- RPA / UiPath ---
  {
    regex:
      /\b(rpa\s*developer|uipath\s*developer|automation\s*anywhere\s*developer|blue\s*prism\s*developer|rpa\s*engineer)\b/i,
    cat: "RPA",
    boost: 5,
  },
  {
    regex: /\b(re-framework|robotic\s*process\s*automation)\b/i,
    cat: "RPA",
    boost: 4,
  },

  // --- DBA ---
  {
    regex:
      /\b(database\s*administrator|dba|database\s*reliability\s*engineer)\b/i,
    cat: "DBA",
    boost: 5,
  },
  {
    regex: /\b(oracle\s*dba|sql\s*server\s*dba|postgres\s*dba|mysql\s*dba)\b/i,
    cat: "DBA",
    boost: 5,
  },

  // --- Management / PM / Program / Scrum ---
  {
    regex:
      /\b(product\s*manager|project\s*manager|program\s*manager|delivery\s*manager|product\s*owner|scrum\s*master|agile\s*coach)\b/i,
    cat: "Management",
    boost: 5,
  },

  // --- Pharma QA ---
  {
    regex: /\b(computer\s*system\s*validation|csv)\b/i,
    cat: "PharmaQA",
    boost: 5,
  },
  {
    regex: /\b(gxp|cgmp|gmp)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(quality\s*management\s*system|qms)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(pharma\s*quality|medical\s*device\s*qa|biotech\s*qa)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex: /\b(validation\s*specialist|validation\s*scientist)\b/i,
    cat: "PharmaQA",
    boost: 4,
  },
  {
    regex:
      /\b(regulatory\s*compliance|inspection\s*readiness|quality\s*auditor)\b/i,
    cat: "PharmaQA",
    boost: 3,
  },
  {
    regex: /\b(capa|apqr|change\s*control)\b/i,
    cat: "PharmaQA",
    boost: 3,
  },
];

export const CITY_ALIAS = {
  bengaluru: [
    "bangalore",
    "bangalore urban",
    "bengaluru, karnataka",
    "bangalore, karnataka",
    "bengaluru, karnataka, india",
    "bangalore, karnataka, india",
    "bengaluru, india",
    "bangalore, india",
    "greater bangalore area",
    "bengaluru area",
    "bangalore area",
    "bengaluru metropolitan region",
    "bangalore metropolitan region",
    "bengaluru east",
    "bengaluru south",
    "electronic city",
    "whitefield",
    "devanahalli",
    "hosur",
    "kolar",
    "ramanagara",
    "tumkur",
    "greater bengaluru area",
  ],
  mumbai: [
    "bombay",
    "mumbai, maharashtra",
    "bombay, maharashtra",
    "mumbai, maharashtra, india",
    "bombay, maharashtra, india",
    "mumbai, india",
    "bombay, india",
    "greater mumbai area",
    "mumbai area",
    "mumbai metropolitan region",
    "mmr",
    "navi mumbai",
    "thane",
    "alibag",
    "khandala",
    "palghar",
    "panvel",
    "sion",
    "ulhasnagar",
  ],
  delhi: [
    "new delhi",
    "delhi ncr",
    "delhi-ncr",
    "ncr",
    "national capital region",
    "national capital region (ncr)",
    "delhi, delhi",
    "new delhi, delhi",
    "delhi, india",
    "new delhi, india",
    "greater delhi area",
    "delhi area",
    "delhi metropolitan area",
  ],
  gurgaon: [
    "gurugram",
    "gurgaon, haryana",
    "gurugram, haryana",
    "gurgaon, haryana, india",
    "gurugram, haryana, india",
    "gurgaon, india",
    "gurugram, india",
    "gurgaon area",
    "gurugram area",
    "gurgaon ncr",
    "gurugram ncr",
    "nuh",
  ],
  noida: [
    "noida, uttar pradesh",
    "noida, uttar pradesh, india",
    "noida, u.p.",
    "noida, up",
    "noida, india",
    "greater noida",
    "greater noida, uttar pradesh",
    "noida extension",
    "noida area",
    "noida ncr",
    "gautam buddha nagar",
  ],
  hyderabad: [
    "hyderabad, telangana",
    "hyderabad, telangana, india",
    "hyderabad, india",
    "greater hyderabad area",
    "hyderabad metropolitan area",
    "hyderabad area",
    "secunderabad",
    "hyderabad/secunderabad",
    "cyberabad",
    "serilingampalli",
  ],
  pune: [
    "pune, maharashtra",
    "pune, maharashtra, india",
    "pune, india",
    "greater pune area",
    "pune area",
    "pune metropolitan region",
    "pmr",
    "hinjewadi",
    "pimpri-chinchwad",
    "pune/pimpri-chinchwad area",
    "chakan",
    "haveli",
    "khed",
    "mulshi",
    "phaltan",
  ],
  chennai: [
    "madras",
    "chennai, tamil nadu",
    "madras, tamil nadu",
    "chennai, tamil nadu, india",
    "madras, tamil nadu, india",
    "chennai, india",
    "madras, india",
    "greater chennai area",
    "chennai metropolitan area",
    "chennai area",
  ],
  kolkata: [
    "calcutta",
    "kolkata, west bengal",
    "calcutta, west bengal",
    "kolkata, west bengal, india",
    "calcutta, west bengal, india",
    "kolkata, india",
    "calcutta, india",
    "greater kolkata area",
    "kolkata metropolitan area",
    "kolkata area",
    "haldia",
  ],
  ahmedabad: [
    "ahmedabad, gujarat",
    "ahmedabad, gujarat, india",
    "ahmedabad, india",
    "amdavad",
    "greater ahmedabad area",
    "ahmedabad area",
    "gandhinagar",
    "gandhinagar, gujarat",
    "ahmedabad-gandhinagar",
  ],
  chandigarh: [
    "chandigarh, chandigarh",
    "chandigarh, india",
    "chandigarh area",
    "greater chandigarh area",
    "chandigarh tricity",
    "mohali",
    "panchkula",
    "mohali district",
    "sahibzada ajit singh nagar",
  ],
  jaipur: [
    "jaipur, rajasthan",
    "jaipur, rajasthan, india",
    "jaipur, india",
    "jaipur area",
    "greater jaipur area",
  ],
  kochi: [
    "cochin",
    "kochi, kerala",
    "cochin, kerala",
    "kochi, kerala, india",
    "cochin, kerala, india",
    "kochi, india",
    "cochin, india",
    "ernakulam",
    "ernakulam, kerala",
    "greater kochi area",
    "kochi area",
  ],
  indore: [
    "indore, madhya pradesh",
    "indore, madhya pradesh, india",
    "indore, m.p.",
    "indore, mp",
    "indore, india",
    "indore area",
    "greater indore area",
  ],
  coimbatore: [
    "coimbatore, tamil nadu",
    "coimbatore, tamil nadu, india",
    "coimbatore, india",
    "kovai",
    "coimbatore area",
    "greater coimbatore area",
  ],
  thiruvananthapuram: [
    "trivandrum",
    "thiruvananthapuram, kerala",
    "trivandrum, kerala",
    "thiruvananthapuram, kerala, india",
    "trivandrum, kerala, india",
    "thiruvananthapuram, india",
    "trivandrum, india",
    "tvm",
    "technopark",
  ],
  visakhapatnam: [
    "vizag",
    "visakhapatnam, andhra pradesh",
    "vizag, andhra pradesh",
    "visakhapatnam, andhra pradesh, india",
    "vizag, andhra pradesh, india",
    "visakhapatnam, india",
    "vizag, india",
    "visakhapatnam area",
    "vizag area",
  ],
  bhubaneswar: [
    "bhubaneswar, odisha",
    "bhubaneswar, orissa",
    "bhubaneswar, odisha, india",
    "bhubaneswar, india",
    "bhubaneswar area",
    "cuttack-bhubaneswar",
  ],
  lucknow: [
    "lucknow, uttar pradesh",
    "lucknow, uttar pradesh, india",
    "lucknow, u.p.",
    "lucknow, up",
    "lucknow, india",
    "lucknow area",
  ],
  bhopal: [
    "bhopal, madhya pradesh",
    "bhopal, madhya pradesh, india",
    "bhopal, india",
  ],
  faridabad: [
    "faridabad, haryana",
    "faridabad, haryana, india",
    "faridabad, india",
  ],
  goa: ["goa, india", "panaji", "panaji, goa", "north goa", "south goa"],
  guwahati: ["guwahati, assam", "guwahati, assam, india", "guwahati, india"],
  jabalpur: [
    "jabalpur, madhya pradesh",
    "jabalpur, madhya pradesh, india",
    "jabalpur, india",
  ],
  jamshedpur: [
    "jamshedpur, jharkhand",
    "jamshedpur, jharkhand, india",
    "jamshedpur, india",
  ],
  kakinada: [
    "kakinada, andhra pradesh",
    "kakinada, andhra pradesh, india",
    "kakinada, india",
  ],
  mysore: [
    "mysore, karnataka",
    "mysore, karnataka, india",
    "mysore, india",
    "mysuru",
  ],
  nagpur: [
    "nagpur, maharashtra",
    "nagpur, maharashtra, india",
    "nagpur, india",
  ],
  nashik: [
    "nashik, maharashtra",
    "nashik, maharashtra, india",
    "nashik, india",
    "greater nashik area",
  ],
  prayagraj: [
    "prayagraj, uttar pradesh",
    "prayagraj, uttar pradesh, india",
    "allahabad",
  ],
  puducherry: [
    "puducherry, puducherry",
    "puducherry, puducherry, india",
    "pondicherry",
  ],
  rajkot: ["rajkot, gujarat", "rajkot, gujarat, india", "greater rajkot area"],
  surat: ["surat, gujarat", "surat, gujarat, india", "surat, india"],
  vadodara: [
    "vadodara, gujarat",
    "vadodara, gujarat, india",
    "baroda",
    "greater vadodara area",
  ],
  vijayawada: [
    "vijayawada, andhra pradesh",
    "vijayawada, andhra pradesh, india",
    "vijayawada east",
  ],
};

const BASE_REMOVE_TITLES = [
  "| India",
  ", India",
  ",India",
  "India",
  "(IND) ",
  "(IND)",
  " (INDIA)",
  "(India)",
  "(India based role – Hyderabad)",
  "- NCR Region",
  " NCR Region",
  "Interesting Job Opportunity",
  "In-Person Hiring Drive- ",
  "In-Person Hiring Drive",
  "Hiring Drive",
  "Hiring Immediately",
  " | Immediate Joiner |",
  "| Immediate Joiner",
  "(Immediate Joiner)",
  "- ASAP Joiner Required",
  "ASAP Joiner Required",
  "#1 Apply fast!",
  "Apply fast!",
  "Great Opportunity in TCS!",
  "Great Opportunity",
];

const cityPrefixes = [
  ", ", // e.g., ", Bangalore"
  ",", // e.g., ",Bangalore"
  "– ", // e.g., "– Bangalore" (en-dash)
  "- ", // e.g., "- Bangalore" (hyphen)
  "-", // e.g., "-Bangalore"
  "| ", // e.g., "| Bangalore"
  " ", // e.g., " Bangalore"
];

/**
 * Generates a Set of remove strings from the CITY_ALIAS object.
 */
function generateCityNameCombos(aliases) {
  const nameCombos = new Set();

  // Get a single, flat array of all aliases (e.g., "bangalore", "whitefield", "ncr")
  const allAliases = Object.values(aliases).flat();

  allAliases.forEach((alias) => {
    if (!alias) {
      return;
    }
    // 1. Create a Title-Cased version (e.g., "bangalore" -> "Bangalore")
    const titleCasedAlias = alias.charAt(0).toUpperCase() + alias.slice(1);
    // 2. Create an Upper-Cased version (e.g., "ncr" -> "NCR")
    const upperCasedAlias = alias.toUpperCase();

    // Apply all prefixes to both versions
    cityPrefixes.forEach((prefix) => {
      // Add the title-cased version (e.g., ", Bangalore", ", Whitefield")
      nameCombos.add(prefix + titleCasedAlias);
      // Only add the all-caps version if it's different and short (4 chars or less)
      // This adds ", NCR" but avoids adding ", BANGALORE URBAN"
      if (titleCasedAlias !== upperCasedAlias && alias.length <= 4) {
        nameCombos.add(prefix + upperCasedAlias);
      }
    });
  });
  return nameCombos;
}

const cityNameCombos = generateCityNameCombos(CITY_ALIAS);
export const REMOVE_TITLES = [
  ...new Set([...BASE_REMOVE_TITLES, ...cityNameCombos]),
];
