window.colors = {
  english: {
    names: [
      { color: "black", label: "BLACK" },
      { color: "brown", label: "BROWN" },
      { color: "grey", label: "GREY" },
      { color: "white", label: "WHITE" },
      { color: "red", label: "RED" },
      { color: "hotpink", label: "PINK" },
      { color: "orange", label: "ORANGE" },
      { color: "yellow", label: "YELLOW" },
      { color: "green", label: "GREEN" },
      { color: "blue", label: "BLUE" },
      { color: "blueviolet", label: "VIOLET" },
      { color: "purple", label: "PURPLE" },
    ],
    locale: "en-US",
  },
  tamil: {
    names: [
      { color: "black", label: "கருப்பு" },
      { color: "brown", label: "பழுப்பு" },
      { color: "grey", label: "சாம்பல்" },
      { color: "white", label: "வெள்ளை" },
      { color: "red", label: "சிவப்பு" },
      { color: "hotpink", label: "இளஞ்சிவப்பு" },
      { color: "orange", label: "ஆரஞ்சு" },
      { color: "yellow", label: "மஞ்சள்" },
      { color: "green", label: "பச்சை" },
      { color: "blue", label: "நீலம்" },
      { color: "blueviolet", label: "ஊதா" },
      { color: "purple", label: "கருஞ்சிவப்பு" },
    ],
    locale: "ta-IN",
  },
  hindi: {
    names: [
      { color: "black", label: "काला" },
      { color: "brown", label: "भूरा" },
      { color: "grey", label: "धूसर" },
      { color: "white", label: "सफेद" },
      { color: "red", label: "लाल" },
      { color: "hotpink", label: "गुलाबी" },
      { color: "orange", label: "नारंगी" },
      { color: "yellow", label: "पीला" },
      { color: "green", label: "हरा" },
      { color: "blue", label: "नीला" },
      { color: "blueviolet", label: "बैंगनी" },
      { color: "purple", label: "जामुनी" },
    ],
    locale: "hi-IN",
  },
  bengali: {
    names: [
      { color: "black", label: "কালো" },
      { color: "brown", label: "বাদামী" },
      { color: "grey", label: "ধূসর" },
      { color: "white", label: "সাদা" },
      { color: "red", label: "লাল" },
      { color: "hotpink", label: "গোলাপি" },
      { color: "orange", label: "কমলা" },
      { color: "yellow", label: "হলুদ" },
      { color: "green", label: "সবুজ" },
      { color: "blue", label: "নীল" },
      { color: "blueviolet", label: "বেগুনী" },
      { color: "purple", label: "রক্তবেগুনী" },
    ],
    locale: "bn-IN",
  },
  telugu: {
    names: [
      { color: "black", label: "నలుపు" },
      { color: "brown", label: "గోధుమ" },
      { color: "grey", label: "బూడిద" },
      { color: "white", label: "తెలుపు" },
      { color: "red", label: "ఎరుపు" },
      { color: "hotpink", label: "గులాబీ" },
      { color: "orange", label: "నారింజ" },
      { color: "yellow", label: "పసుపు" },
      { color: "green", label: "ఆకుపచ్చ" },
      { color: "blue", label: "నీలం" },
      { color: "blueviolet", label: "వైలెట్" },
      { color: "purple", label: "ఊదా" },
    ],
    locale: "te-IN",
  },
  kannada: {
    names: [
      { color: "black", label: "ಕಪ್ಪು" },
      { color: "brown", label: "ಕಂದು" },
      { color: "grey", label: "ಬೂದು" },
      { color: "white", label: "ಬಿಳಿ" },
      { color: "red", label: "ಕೆಂಪು" },
      { color: "hotpink", label: "ಗುಲಾಬಿ" },
      { color: "orange", label: "ಕಿತ್ತಳೆ" },
      { color: "yellow", label: "ಹಳದಿ" },
      { color: "green", label: "ಹಸಿರು" },
      { color: "blue", label: "ನೀಲಿ" },
      { color: "blueviolet", label: "ನೀಲಿ ನೇರಳೆ" },
      { color: "purple", label: "ನೇರಳೆ" },
    ],
    locale: "kn-IN",
  },
  malayalam: {
    names: [
      { color: "black", label: "കറുപ്പ്" },
      { color: "brown", label: "തവിട്ടുനിറം" },
      { color: "grey", label: "ചാരനിറം" },
      { color: "white", label: "വെള്ള" },
      { color: "red", label: "ചുവപ്പ്" },
      { color: "hotpink", label: "പിങ്ക്" },
      { color: "orange", label: "ഓറഞ്ച്" },
      { color: "yellow", label: "മഞ്ഞ" },
      { color: "green", label: "പച്ച" },
      { color: "blue", label: "നീല" },
      { color: "blueviolet", label: "വയലറ്റ്" },
      { color: "purple", label: "ധൂമ്രനൂൽ" },
    ],
    locale: "ml-IN",
  },
  gujarati: {
    names: [
      { color: "black", label: "કાળો" },
      { color: "brown", label: "ભૂરો" },
      { color: "grey", label: "ગ્રે" },
      { color: "white", label: "સફેદ" },
      { color: "red", label: "લાલ" },
      { color: "hotpink", label: "ગુલાબી" },
      { color: "orange", label: "નારંગી" },
      { color: "yellow", label: "પીળો" },
      { color: "green", label: "લીલો" },
      { color: "blue", label: "વાદળી" },
      { color: "blueviolet", label: "વાયોલેટ" },
      { color: "purple", label: "જાંબલી" },
    ],
    locale: "gu-IN",
  },
  punjabi: {
    names: [
      { color: "black", label: "ਕਾਲਾ" },
      { color: "brown", label: "ਭੂਰਾ" },
      { color: "grey", label: "ਸਲੇਟੀ" },
      { color: "white", label: "ਚਿੱਟਾ" },
      { color: "red", label: "ਲਾਲ" },
      { color: "hotpink", label: "ਗੁਲਾਬੀ" },
      { color: "orange", label: "ਸੰਤਰੀ" },
      { color: "yellow", label: "ਪੀਲਾ" },
      { color: "green", label: "ਹਰਾ" },
      { color: "blue", label: "ਨੀਲਾ" },
      { color: "blueviolet", label: "ਵਾਇਲੇਟ" },
      { color: "purple", label: "ਬੈਂਗਣੀ" },
    ],
    locale: "pa-IN",
  },
  urdu: {
    names: [
      { color: "black", label: "کالا" },
      { color: "brown", label: "بھورا" },
      { color: "grey", label: "سلیٹی" },
      { color: "white", label: "سفید" },
      { color: "red", label: "سرخ" },
      { color: "hotpink", label: "گلابی" },
      { color: "orange", label: "نارنجی" },
      { color: "yellow", label: "پیلا" },
      { color: "green", label: "سبز" },
      { color: "blue", label: "نیلا" },
      { color: "blueviolet", label: "بنفشی" },
      { color: "purple", label: "جامنی" },
    ],
    locale: "ur-IN",
  },
};
